### ISSUE TITLE
Missing null checks

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1039]
I'm playing around with [nullable reference types](https://devblogs.microsoft.com/dotnet/nullable-reference-types-in-csharp/) in [this branch](https://github.com/jnyrup/fluentassertions/tree/nullableReferenceTypes).
So far I've found several places that could benefit from an extra null check.

I'll try to keep the branch in sync with master as the null checks are merged.

```
ReferenceTypeAssertions
	BeAssignableTo
	BeAssignableTo<T>
		null Subject

ComparableTypeAssertions
	Be
		null Subject
	
NumericAssertions
	BeOfType
	NotBeOfType
		null Subject
		
ObjectAssertions
	HaveFlag
	NotHaveFlag
		null expectedFlag
		
ActionAssertions
	NotThrow
	InvokeSubjectWithInterception (public methods that calls it)
		null Subject
		
AsyncFunctionAssertions
	NotThrow
	NotThrowAsync
	NotThrow<TException>
	NotThrowAsync<TException>
	InvokeSubjectWithInterception (public methods that calls it)
	InvokeSubjectWithInterceptionAsync (public methods that calls it)
		null Subject
		
FunctionAssertions
	NotThrow
	NotThrow<TException>
	InvokeSubjectWithInterception (public methods that calls it)
	NotThrowAfter
		null Subject
		
AssemblyAssertions
	DefineType
		null Subject
	Reference
	NotReference
		null Subject
		null assembly
		
ExecutionTimeAssertions
	ctor
		null action
		null Func<T>
		
SimpleTimeSpanAssertions
	BePositive
	BeNegative
	Be
	NotBe
	BeLessThan
	BeLessOrEqualTo
	BeGreaterThan
	BeGreaterOrEqualTo
		null Subject
```

**Comment by dennisdoomen** [comment]
You know C# 8 is still in preview, don't  you?

**Comment by jnyrup** [comment]
I sure know that C# 8 is still in preview, that's why I keep the nullable annotation changes in a branch, which I have no intentions to create a PR on right now. 
That said, nullable reference types are already a great tool to let the compiler spot places with insufficient null checks.
My intention with this issue is to bring attention to those missing null checks, such that they can be added to master.

**Comment by jnyrup** [comment]
I hacked up some [reflection code](https://github.com/jnyrup/fluentassertions/tree/nullReflection) in my search to eliminate `NullReferenceException`s thrown from FA.

It found 92 ways where we could throw a `NullReferenceException`.
[NullReferenceExceptions.txt](https://github.com/fluentassertions/fluentassertions/files/3509387/NullReferenceExceptions.txt)

**Comment by jnyrup** [comment]
Yay - we're down to 83
[NullReferenceExceptions.txt](https://github.com/fluentassertions/fluentassertions/files/5564943/NullReferenceExceptions.txt)

**Comment by eNeRGy164** [comment]
I'm looking at making the `TypeAssertions` a bit more robust. This will take quite a bite out of this list

**Comment by eNeRGy164** [comment]
Basically it comes down to fix the arguments for the following classes
* `PropertyInfoAssertions`
* `AssemblyAssertions`
* `MethodInfoAssertions`
* `TypeSelectorAssertions`
* `XDocumentAssertions`

**Comment by eNeRGy164** [comment]
Have a PR prepared for `PropertyInfoAssertions` as soon #1550 is in.

**Comment by jnyrup** [comment]
Down to 54
[NullReferenceExceptions.txt](https://github.com/fluentassertions/fluentassertions/files/6477250/NullReferenceExceptions.txt)

**Comment by jnyrup** [comment]
32
[NullReferenceExceptions.txt](https://github.com/fluentassertions/fluentassertions/files/6482484/NullReferenceExceptions.txt)

**Comment by jnyrup** [comment]
The test code now wraps invocations in an `AssertionScope` to catch more potentially unsafe code.

So we're down to 9 🎉 
[NullReferenceExceptions.txt](https://github.com/fluentassertions/fluentassertions/files/6537332/NullReferenceExceptions.txt)

The exception from `ShouldExcludeColumn` is being solved in #1578

**Comment by eNeRGy164** [comment]
I was looking into this, but I can't reproduce it for `HaveLength`

```csharp
public void When_asserting_string_length_on_null_string_it_should_fail()
{
    // Arrange
    string actual = null;

    // Act
    Action act = () =>
    {
        using var _ = new AssertionScope();
        actual.Should().HaveLength(0, "we want to test the failure {0}", "message");
    };

    // Assert
    act.Should().Throw<XunitException>()
        .WithMessage("Expected actual with length 0 *failure message*, but found <null>.");
}
```

is successful without alteration

```csharp
public AndConstraint<TAssertions> HaveLength(int expected, string because = "", params object[] becauseArgs)
{
    Execute.Assertion
        .BecauseOf(because, becauseArgs)
        .ForCondition(Subject is not null)
        .FailWith("Expected {context:string} with length {0}{reason}, but found <null>.", expected)
        .Then
        .ForCondition(Subject.Length == expected)
        .FailWith("Expected {context:string} with length {0}{reason}, but found string {1} with length {2}.",
            expected, Subject, Subject.Length);

    return new AndConstraint<TAssertions>((TAssertions)this);
}
```

**Comment by jnyrup** [comment]
If you attach a debugger, you should be able to see the exception.

**Comment by eNeRGy164** [comment]
> If you attach a debugger, you should be able to see the exception.

Ah, indeed, makes it a bit harder to confirm the correct working with a red/green unit test?

**Comment by jnyrup** [comment]
It indeed does and on the top of my head I don't have a pretty way to tests it.

Here's a not very satisfying way to catch it.
```cs
[Fact]
public void When_asserting_string_length_on_null_string_it_should_fail()
{
    // Arrange
    string actual = null;

    // Act
    Action act = () =>
    {
        using var scope = new AssertionScope();
        try
        {
            actual.Should().HaveLength(0, "we want to test the failure {0}", "message");
        }
        catch (Exception e)
            when (e is not XunitException)
        {
            // <-- catches the NullReferenceException
        }
    };
}
```

**Comment by eNeRGy164** [comment]
I could not reproduce the NRE on `BeCloseTo` to line 52 of `PollUntil`.

I did find the following cases that were not detected yet:

```csharp
Action someAction = null;
Action act = () => someAction.ExecutionTime().Should().BeCloseTo(100.Milliseconds(), 50.Milliseconds());

Func<Task> someAction = null;
Action act = () => someAction.ExecutionTime().Should().BeCloseTo(100.Milliseconds(), 50.Milliseconds());
act.Should().NotThrow<NullReferenceException>();

var subject = new SleepingClass();
Action act = () => subject.ExecutionTimeOf(null).Should().BeLessOrEqualTo(500.Milliseconds());
act.Should().NotThrow<NullReferenceException>();

Does someClass = Does.NotThrow();
someClass.Invoking(null).Should().NotThrow<NullReferenceException>();
```

This one is swallowed:

```csharp
var asyncObject = new AsyncClass();
Func<Task> act = () => asyncObject.Awaiting(x => null).Should().ThrowAsync<InvalidOperationException>();
await act.Should().NotThrowAsync<NullReferenceException>();
```

**Comment by eNeRGy164** [comment]
Hi @jnyrup, I ran your test yesterday and it seems there are no error detected anymore?

I did look at the code to inject `null` arrays (`new [] { null }`) but I gave up, too complex all those `yield`s 😛

**Comment by jnyrup** [comment]
It is indeed some hacky Friday evening code 😅 

I still find these, but they seem pretty obscure.
E.g. inheriting from a Regex using the protected parameterless base constructor and returning null from `ToString()`.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentAssertions.Primitives.StringAssertions`1.MatchRegex(Regex regularExpression, String because, Object[] becauseArgs) in C:\dev\fluentassertions\Src\FluentAssertions\Primitives\StringAssertions.cs:line 440
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentAssertions.Primitives.StringAssertions`1.NotMatchRegex(Regex regularExpression, String because, Object[] becauseArgs) in C:\dev\fluentassertions\Src\FluentAssertions\Primitives\StringAssertions.cs:line 516
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.DelegateSerializationHolder.GetDelegateSerializationInfo(SerializationInfo info, Type delegateType, Object target, MethodInfo method, Int32 targetIndex)
   at System.MulticastDelegate.GetObjectData(SerializationInfo info, StreamingContext context)
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentAssertions.Data.DataEquivalencyAssertionOptions`1.ShouldExcludeColumn(DataColumn column) in C:\dev\fluentassertions\Src\FluentAssertions\Data\DataEquivalencyAssertionOptions.cs:line 305
   at FluentAssertions.Equivalency.DataColumnEquivalencyStep.CompareSubjectAndExpectationOfTypeDataColumn(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator parent, DataColumn subject) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataColumnEquivalencyStep.cs:line 57
   at FluentAssertions.Equivalency.DataColumnEquivalencyStep.OnHandle(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator nestedValidator) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\DataColumnEquivalencyStep.cs:line 41
   at FluentAssertions.Equivalency.EquivalencyStep`1.Handle(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator nestedValidator) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyStep.cs:line 15
   at FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(Comparands comparands, IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 65
   at FluentAssertions.Equivalency.EquivalencyValidator.RecursivelyAssertEquality(Comparands comparands, IEquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 37
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context) in C:\dev\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 19
   at FluentAssertions.Data.DataColumnAssertions.BeEquivalentTo(DataColumn expectation, Func`2 config, String because, Object[] becauseArgs) in C:\dev\fluentassertions\Src\FluentAssertions\Data\DataColumnAssertions.cs:line 131
   at FluentAssertions.Data.DataColumnAssertions.BeEquivalentTo(DataColumn expectation, String because, Object[] becauseArgs) in C:\dev\fluentassertions\Src\FluentAssertions\Data\DataColumnAssertions.cs:line 59
```

If the tool should be improved, I would probably go for handling methods with generic parameters.
But I think we've handled a lot the obvious exception for now.

Running the tool in debug mode and breaking on NREs revealed a few more potential places
```
AsyncFunctionAssertions (and probably the other delegate based assertions)
null Subject

public static Action Enumerating(this Func<IEnumerable> enumerable) 
null enumerable
```

**Comment by eNeRGy164** [comment]
I think a lot of collection methods also obscure a lot as they tend to wrap a lot of `AssertionScope`s in their flow

**Comment by jnyrup** [comment]
Haven't tested these, but searched for `ForCondition.* is not null` and found some more

```
Search for "ForCondition.* is not null"

HaveProperty
	propertyInfo
	
HaveIndexer
	propertyInfo
	
TaskCompletionSourceAssertions
GenericAsyncFunctionAssertions
FunctionAssertions
ExceptionAssertions
	WithInnerException
DelegateAssertionsBase	
	Throw<TException>
DelegateAssertions
AsyncFunctionAssertions
AssemblyAssertions

ReferenceTypeAssertions
	[Not]BeOfType
	[Not]BeAssignableTo
	
	
StringCollectionAssertions
	[Not]ContainMatch
	
GenericCollectionAssertions
	AllBeAssignableTo x2
	AllBeOfType x2
	BeEmpty
	NotBeSubsetOf
	NotContainEquivalentOf
	SatisfyRespectively
	Satisfy
	
NumericAssertionsExtensions
```

**Comment by eNeRGy164** [comment]
`HaveProperty`, `HaveIndexer` and `AssemblyAssertions` are wrapped in `if (success)` statements by my PR's

**Comment by jnyrup** [comment]
Forgot to mention that for `HaveProperty` and `HaveIndexer` I was looking at `propertyInfo` and not `Subject`

**Comment by eNeRGy164** [comment]
> Forgot to mention that for `HaveProperty` and `HaveIndexer` I was looking at `propertyInfo` and not `Subject`

You mean the return statement returning a null property? Yes, I noticed that when adding the if statement. I don't know how we should handle that differently.

**Comment by eNeRGy164** [comment]
I'll pick up `ReferenceTypeAssertions`, `StringCollectionAssertions` and `
GenericCollectionAssertions` first. I have confirmed the NRE's in all those methods

**Comment by eNeRGy164** [comment]
You should also do a search on `Subject is null` 😭 the list keeps growing

**Comment by eNeRGy164** [comment]
> I'll pick up `ReferenceTypeAssertions`, `StringCollectionAssertions` and ` GenericCollectionAssertions` first. I have confirmed the NRE's in all those methods

So, that were only 50 methods (excluding overloads)... pfff
