### ISSUE TITLE
NullReferenceException in BeEquivalentTo() usage with "Using" and "When" EquivalencyAssertationOptions

### ISSUE THREAD

**Issue by myatmin** [fluentassertions/fluentassertions#1093]
### "When" usage throws NullReferenceException after "Using" EquivalencyAssertionOptions
Test objects have the same type and it has CreatedDate, UpdatedDate properties.

### Test Code:
```csharp

input.Should().BeEquivalentTo(result, options => options
    .Using<DateTime>(context => context.Subject.Should().BeCloseTo(context.Expectation, 1000))
    .When(info => info.SelectedMemberPath.EndsWith("Date")));
```
### Actual behavior:
```csharp
Result1 StackTrace:	
at FluentAssertions.Equivalency.AssertionContext`1.CreateFromEquivalencyValidationContext(IEquivalencyValidationContext context) in C:\Workspaces\fluentassertions\src\FluentAssertions\Equivalency\AssertionContext.cs:line 29
   at FluentAssertions.Equivalency.AssertionRule`1.AssertEquality(IEquivalencyValidationContext context) in C:\Workspaces\fluentassertions\src\FluentAssertions\Equivalency\AssertionRule.cs:line 57
   at FluentAssertions.Equivalency.AssertionRuleEquivalencyStepAdapter.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\Workspaces\fluentassertions\src\FluentAssertions\Equivalency\AssertionRuleEquivalencyStepAdapter.cs:line 22
   at FluentAssertions.Equivalency.RunAllUserStepsEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\Workspaces\fluentassertions\src\FluentAssertions\Equivalency\RunAllUserStepsEquivalencyStep.cs:line 21
   at FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(IEquivalencyValidationContext context) in C:\Workspaces\fluentassertions\src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 119
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\Workspaces\fluentassertions\src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 54
   at FluentAssertions.Equivalency.StructuralEqualityEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\Workspaces\fluentassertions\src\FluentAssertions\Equivalency\StructuralEqualityEquivalencyStep.cs:line 46
   at FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(IEquivalencyValidationContext context) in C:\Workspaces\fluentassertions\src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 119
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\Workspaces\fluentassertions\src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 54
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\Workspaces\fluentassertions\src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 37
   at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs) in C:\Workspaces\fluentassertions\src\FluentAssertions\Primitives\ObjectAssertions.cs:line 123

Result1 Message:	System.NullReferenceException : Object reference not set to an instance of an object.
Result1 StandardOutput:
Result1 StandardError:

```

### Versions
FluentAssertions V5.7.0
.NET framework 4.6.1

### Additional Information
Test adapted from "Equivalency Comparison Behavior" of [https://fluentassertions.com/objectgraphs/](https://fluentassertions.com/objectgraphs/)

**Comment by dennisdoomen** [comment]
It's probably `SelectedMemberPath` that returns `null`. It does that when you're still at the root of the graph. The documentation sucks and we probably should return a nicer error messag.e

**Comment by myatmin** [comment]
Oh, I see!
Now I used below to avoid the runtime null referencing since my test object value has null assignment on the DateTime type and I still wanted to filter with the property name. Thank you! 👍 

``` csharp
options.Using<DateTime>(context => context.Subject.Should().BeCloseTo(context.Expectation, 1000))
.When(info => info.RuntimeType == typeof(DateTime) && info.SelectedMemberPath.EndsWith("Date"));

**Comment by dennisdoomen** [comment]
Or you could have used `info.SelectedMemberPath?.EndsWith("Date")`

**Comment by myatmin** [comment]
Oh, yeah, totally forgot about it! Brilliant!
Thank you so much! 😃

**Comment by myatmin** [comment]
Unfortunately, lambda does not allow for the null propagation operator.
I will stick to the old solution for the time being.

![image](https://user-images.githubusercontent.com/359522/60933128-96119c80-a2f3-11e9-98d6-676e1f3c251e.png)

If lambda take null propagation opreator, it could be same syntax as below but path still will be avaliable and won't be preventing from the error still I guess.

```csharp
options.Using<DateTime>(context => context.Subject.Should().BeCloseTo(context.Expectation, 1000)).When(info => info.SelectedMemberPath != null && info.SelectedMemberPath.EndsWith("Date"));

**Comment by dennisdoomen** [comment]
Maybe we should change that property to never return `null` and return an empty string instead.

**Comment by myatmin** [comment]
Yes, agree with you. 😃

**Comment by jnyrup** [comment]
By looking at the provided stack trace and the fact that the property types sounds to be `DateTime?` this is caused by #799.
`SelectedMemberPath` is not null, it's `SelectedMemberInfo` that can be null.
