### ISSUE TITLE
Dictionary equivalence fails for reference type keys

### ISSUE THREAD

**Issue by ackginger** [fluentassertions/fluentassertions#1136]
### Description
When comparing two identical dictionaries which use an object as the key, `.Should().BeEquivalentTo()` fails.

If I override `.Equals()` then it succeeds, which feels like it goes against the principle of equivalence expectations.

Whilst this may be my misunderstanding of the expectation, the docs don't seem to call this limitation out, so perhaps worth documenting if deemed by design.

### Complete minimal example reproducing the issue

```csharp
using System.Collections.Generic;
using FluentAssertions;
using Xunit;

namespace Repro
{
    public class TestFluentAssertions
    {
        [Fact]
        public void ObjectKeyDictEquivalence()
        {
            var original = new Dictionary<TestKey, string>
            {
                [new TestKey {A = 1, B = 2}] = "value 1",
                [new TestKey {A = 1000, B = 2000}] = "value 2"
            };

            var copy = new Dictionary<TestKey, string>
            {
                [new TestKey {A = 1, B = 2}] = "value 1",
                [new TestKey {A = 1000, B = 2000}] = "value 2"
            };

            copy.Should().BeEquivalentTo(original, opts => opts.WithTracing());
        }
    }

    public class TestKey
    {
        public int A { get; set; }

        public int B { get; set; }
    }
}
```

### Expected behavior:

Expectation passes

### Actual behavior:

```
Repro.TestFluentAssertions.ObjectKeyDictEquivalence

Expected copy to contain key 

Repro.TestKey
{
   A = 1
   B = 2
}.
Expected copy to contain key 

Repro.TestKey
{
   A = 1000
   B = 2000
}.

With configuration:
- Use declared types and members
- Compare enums by value
- Match member by name (or throw)
- Without automatic conversion.
- Be strict about the order of items in byte arrays

With trace:

   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\CollectingAssertionStrategy.cs:line 52
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 44
   at Repro.TestFluentAssertions.ObjectKeyDictEquivalence() in C:\...\Repro.cs:line 24
```

### Versions

Fluent Assertions 5.9.0
xUnit 2.4.1
.Net Core 2.2.0

**Comment by dennisdoomen** [comment]
The keys itself are not compared for equivalency. Although it could theoretically be done, it would complicate comparing the the dictionaries quite a lot. You would have to find a key in the other dictionary that is the closest in terms of equivalency, and then ensure the values are equivalent.

**Comment by ackginger** [comment]
Ok, that makes sense, although couldn't you just compare it as a collection of KVPs?

The docs definitely don't make this clear though. The dictionary section says:

> You can also assert the equality of the entire dictionary, where the equality of the keys and values will be validated using their Equals implementation

which is clear since it's talking about equality, but then the object graph comparison section does not mention this in the collections and dictionaries sub-section.

**Comment by dennisdoomen** [comment]
You're using `BeEquivalentTo` which is about the structural equivalence. I admit that the docs are not very clear.

**Comment by ackginger** [comment]
Sorry, yes, I understand that, what I mean is that the method of comparison is called out explicitly for `Equal` on the dictionary page, but no matching detail for `BeEquivalentTo`.

Beyond documentation, what if you just compare it as ICollection<KeyValuePair<TKey, TValue>> if the key type does not support value semantics?

For example, my sample above can be made to pass by using:

```csharp
((ICollection<KeyValuePair<TestKey, string>>)copy).Should().BeEquivalentTo(original, opts => opts.WithTracing());
```

Obviously this isn't possible deeper down the object graph without very specific targeting of comparison behaviour. Given dictionaries with types which don't support object equality cannot ever be compared successfully using `BeEquivalentTo` currently then this would be a nice enhancement.

**Comment by bzaar** [comment]
Would be nice to have this as an option. My expectation was too, keys should be compared by value.

**Comment by dennisdoomen** [comment]
IMO, keys are identifiers and should never be loosely compared. Sure, we could provide an option for that, but I'm not sure it would make sense a lot.

**Comment by bzaar** [comment]
Just to avoid any doubt, It's not about loosely or strictly, it's about by ref / by value. IMHO, keys should be compared by value. :) 
This allows for compound keys which can be super useful.

**Comment by dennisdoomen** [comment]
That's what I meant as well. Normally, a dictionary will compare keys by using the default `EqualityComparer` for that type. What you are asking for is to use the equivalency algorithm that `BeEquivalentTo` normally uses to compare the keys. That would significantly slow down the comparison, but also result in some fuzzy comparisons. For example, a key consisting of a complex type with several properties will match with an object that has only two matching properties with matching values.

**Comment by bzaar** [comment]
> a key consisting of a complex type with several properties will match with an object that has only two matching properties with matching values.

@dennisdoomen: You mean, ```new {A=1, B=2, C=3}``` will match ```new {A=1, B=2}```? Is this how ```BeEquivalentTo``` currently works?

**Comment by dennisdoomen** [comment]
If the first is the subject-under-test and the second is the expectation, yes.
