### ISSUE TITLE
NotBeNull fails when using custom assertions

### ISSUE THREAD

**Issue by stanac** [fluentassertions/fluentassertions#1511]
### Description

I might be missing something, I have followed [Extensibility guide](https://fluentassertions.com/extensibility/).

If custom assertions is defined with extension on a class, calling `Should().NotBeNull()` on object of that class will fail when object is not null.

### Complete minimal example reproducing the issue

I have created [a repo](https://github.com/stanac/FluentAssertionsTest) for easy reproduction of the issue.

Following code works ok:

```csharp
public class PersonModel
{
    public string Name { get; set; }
}

public class Test
{
    [Fact]
    public void PersonSetName_NameIsSet()
    {
        var p = new PersonModel { Name = "A" };
    
        p.As<object>().Should().NotBeNull(); // always passes
        p.Should().NotBeNull(); // fails when custom assertion is defined
    }
}
```

However if custom assertions is defined as below, `p.Should().NotBeNull();` will fail

```csharp
public static class PersonModelAssertionsExtensions
{
    public static PersonModelAssertions Should(this PersonModel p) => new PersonModelAssertions(p);
}

public class PersonModelAssertions : ReferenceTypeAssertions<PersonModel, PersonModelAssertions>
{
    protected override string Identifier => typeof(PersonModelAssertions).FullName;

    private readonly PersonModel _person;

    public PersonModelAssertions(PersonModel person)
    {
        _person = person;
    }

    [CustomAssertion]
    public AndConstraint<PersonModelAssertions> HaveNameSet(string because, params string[] becauseArgs)
    {
        Execute.Assertion
            .ForCondition(_person != null && !string.IsNullOrWhiteSpace(_person.Name))
            .BecauseOf(because, becauseArgs)
            .FailWith("Expected {context:element} to be set");

        return new AndConstraint<PersonModelAssertions>(this);
    }
}
```

### Expected behavior:

Test `PersonSetName_NameIsSet` should always pass

### Actual behavior:

When `PersonModelAssertionsExtensions` and `PersonModelAssertions` are defined, test fails with following:

```
d:\repos\github\temp\FluentAssertionsTest>dotnet test
  Determining projects to restore...
  Restored d:\repos\github\temp\FluentAssertionsTest\FluentAssertionsTest.csproj (in 418 ms).
  FluentAssertionsTest -> d:\repos\github\temp\FluentAssertionsTest\bin\Debug\net5.0\FluentAssertionsTest.dll
Test run for d:\repos\github\temp\FluentAssertionsTest\bin\Debug\net5.0\FluentAssertionsTest.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.8.3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.74]     FluentAssertionsTest.Test.PersonSetName_NameIsSet [FAIL]
  Failed FluentAssertionsTest.Test.PersonSetName_NameIsSet [89 ms]
  Error Message:
   Expected p not to be <null>.
  Stack Trace:
     at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.NotBeNull(String because, Object[] becauseArgs)
   at FluentAssertionsTest.Test.PersonSetName_NameIsSet() in d:\repos\github\temp\FluentAssertionsTest\Test.cs:line 49

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 89 ms - FluentAssertionsTest.dll (net5.0)
```

### Versions

* Which version of Fluent Assertions are you using? 5.10.3
* Which .NET runtime and version are you targeting? .NET 5 and .NET Core 3.1

### Additional Information

If new `NotBeNull` method is defined in `PersonModelAssertions`  test will pass.

I have tried to inherit `ReferenceTypeAssertions<object, PersonModelAssertions>` instead of `ReferenceTypeAssertions<PersonModel, PersonModelAssertions>` without difference.

`.csproj` looks like this, I have also reproduced the same issue with `<TargetFramework>netcoreapp3.1</TargetFramework>`

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="1.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.10.3" />
  </ItemGroup>

</Project>
```

**Comment by dennisdoomen** [comment]
You forgot to use the pass the person to the base class by using the `: base(_person)` call in your constructor. See for example how the [string assertions](https://github.com/fluentassertions/fluentassertions/blob/a26aaea53a3f3e30c7a76e537c27cd2c66237200/Src/FluentAssertions/Primitives/StringAssertions.cs#L38) do that.

**Comment by stanac** [comment]
@dennisdoomen you are absolutely right, thank you, it works now

closing the ticket

**Comment by jnyrup** [comment]
In the upcoming Fluent Assertions 6.0 we have removed the parameterless constructor of `ReferenceTypeAssertions` _exactly_ to prevent this scenario. #1229.
