### ISSUE TITLE
Excluding not functioning on overridden covariant property

### ISSUE THREAD

**Issue by taylorn16** [fluentassertions/fluentassertions#1562]
### Description

Excluding not functioning on overridden covariant property.

See https://github.com/fluentassertions/fluentassertions/issues/1077#issuecomment-830863819 for original context.

### Complete minimal example reproducing the issue

```csharp
using FluentAssertions;

public class BaseProp
{
    public string BaseVal { get; set; }
}

public class DerivedProp : BaseProp
{
    public string DerivedVal { get; set; }
}

public abstract class Base
{
    public abstract BaseProp Prop { get; }
}

public sealed class Derived : Base
{
    public override DerivedProp Prop { get; }
    public string OtherProp { get; set; }
    
    public Derived(DerivedProp prop)
    {
        Prop = prop;
    }
}

public class Program
{
    public static void Main()
    {
        var a = new Derived(new DerivedProp { DerivedVal = "a", BaseVal = "a_base" })
        {
            OtherProp = "other"
        };
        var b = new Derived(new DerivedProp { DerivedVal = "b", BaseVal = "b_base" })
        {
	        OtherProp = "other"
        };
        
        a.Should().BeEquivalentTo(b, opts => opts
                                            .ComparingByMembers<Derived>()
                                            .Excluding(d => d.Prop));
    }
}
```

### Expected behavior:

The `.Should().BeEquivalentTo` call should result in no test failure exception being thrown.

### Actual behavior:

```
Unhandled exception. FluentAssertions.Execution.AssertionFailedException: Expected member Prop.BaseVal to be "b_base", but "a_base" differs near "a_b" (index 0).

With configuration:
- Use declared types and members
- Compare enums by value
- Exclude member root.Prop
- Match member by name (or throw)
- Without automatic conversion.
- Be strict about the order of items in byte arrays

   at FluentAssertions.Execution.FallbackTestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\FallbackTestFramework.cs:line 18
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\TestFrameworkProvider.cs:line 40
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\CollectingAssertionStrategy.cs:line 44
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 43
   at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\ObjectAssertions.cs:line 125
   at Program.Main()
Command terminated by signal 6
```

### Versions

* FluentAssertions 5.10.3
* .NET 5

**Comment by dennisdoomen** [comment]
> Hmm, I can reproduce this as well. But as soon as I remove Prop from Base, it succeeds. So it's something with the covariant property declaration that's causing issues. I suspect that this looks like the same problem that was reported in this issue, but in reality it's a different issue. @taylorn16 would you mind creating a new issue for this?

**Comment by jnyrup** [comment]
I've tried looking into this.

`private static PropertyInfo[] GetPublicProperties(Type type)` on `Derived`, which gets us

```cs
[0]: {DerivedProp Prop}
[1]: {System.String OtherProp}
[2]: {BaseProp Prop}
[3]: {System.String BaseProp}
```

The best documentation I've found about how to distinguish covariant types is https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/covariant-returns#name-lookup

A workaround is to also exclude `Base.Prop` even though it triggers a "cast is redundant" analyzer.

```cs
var a = new Derived(new DerivedProp { DerivedVal = "a", BaseVal = "a_base" });
var b = new Derived(new DerivedProp { DerivedVal = "b", BaseVal = "b_base" });

a.Should().BeEquivalentTo(b, opts => opts
    .Excluding(d => ((Base)d).Prop)
    .Excluding(d => d.Prop));
```

`Derived_Derived` fails even though `Derived.Prop` is excluded as `Base.Prop` is still included.

`Base_Derived` throws a `Reflection.TargetException`.
From `Derived` we reflect the property `Base.Prop`, which has `GetMethod = {DerivedProp get_Prop()}`.
So when invoking `PropertyInfo.GetValue` on an instance of `Base` it throws the exception.

```cs
public class BaseProp
{
    public string BaseVal { get; set; }
}

public class DerivedProp : BaseProp
{
    public string DerivedVal { get; set; }
}

public class Base
{
    public Base(BaseProp prop) => Prop = prop;

    protected Base() { }

    public virtual BaseProp Prop { get; }

    public string BaseProp { get; set; }
}

public sealed class Derived : Base
{
    public override DerivedProp Prop { get; }

    public string OtherProp { get; set; }

    public Derived(DerivedProp prop) => Prop = prop;
}

[Fact]
public void Base_Base()
{
    var a = new Base(new BaseProp { BaseVal = "a_base" });
    var b = new Base(new BaseProp { BaseVal = "b_base" });

    a.Should().BeEquivalentTo(b, opts => opts
        .Excluding(d => d.Prop));
}

[Fact]
public void Base_Derived()
{
    var a = new Base(new BaseProp { BaseVal = "a_base" });
    var b = new Derived(new DerivedProp { DerivedVal = "b", BaseVal = "b_base" });

    a.Should().BeEquivalentTo(b, opts => opts
        .Excluding(d => d.OtherProp)
        .Excluding(d => d.Prop));
}

[Fact]
public void Derived_Base()
{
    var a = new Derived(new DerivedProp { DerivedVal = "a", BaseVal = "a_base" });
    var b = new Base(new BaseProp { BaseVal = "b_base" });

    a.Should().BeEquivalentTo(b, opts => opts
        .Excluding(d => d.Prop));
}

[Fact]
public void Derived_Derived()
{
    var a = new Derived(new DerivedProp { DerivedVal = "a", BaseVal = "a_base" });
    var b = new Derived(new DerivedProp { DerivedVal = "b", BaseVal = "b_base" });

    a.Should().BeEquivalentTo(b, opts => opts
        .Excluding(d => d.Prop));
}
```

**Comment by dennisdoomen** [comment]
So? Can we even fix this?
