### ISSUE TITLE
Satisfy doesn't support extension methods

### ISSUE THREAD

**Issue by Bouke** [fluentassertions/fluentassertions#1688]
### Description

Calling an extension method from the expression provided to `Satisfy` causes an exception. I think this shouldn't happen and calling extension methods should work.

### Complete minimal example reproducing the issue

```csharp
// Fails: IEnumerable<int>.Contains is an extension method
var actual = new[] { 1, 2, 3 };
var allowed = new[] { 1, 2, 3 };
actual.Should().Satisfy(
	x => allowed.Contains(x),
	x => allowed.Contains(x),
	x => allowed.Contains(x));

// Works: HashSet<int>.Contains is not an extension method
var actual = new[] { 1, 2, 3 };
var allowed = new HashSet<int> { 1, 2, 3 };
actual.Should().Satisfy(
	x => allowed.Contains(x),
	x => allowed.Contains(x),
	x => allowed.Contains(x));
```

### Expected behavior:
Should work.

### Actual behavior:
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'body')
   at System.Linq.Expressions.Expression.Lambda(Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda(Expression body, ParameterExpression[] parameters)
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.ConstantSubExpressionReductionVisitor.Visit(Expression node) in /_/Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs:line 86
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.ConstantSubExpressionReductionVisitor.Visit(Expression node) in /_/Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs:line 89
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.ReduceConstantSubExpressions(Expression expression) in /_/Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs:line 40
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.Format(Object value, FormattedObjectGraph formattedGraph, FormattingContext context, FormatChild formatChild) in /_/Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs:line 17
   at FluentAssertions.Formatting.Formatter.Format(Object value, FormattedObjectGraph output, FormattingContext context, FormatChild formatChild) in /_/Src/FluentAssertions/Formatting/Formatter.cs:line 153
   at FluentAssertions.Formatting.Formatter.ToString(Object value, FormattingOptions options) in /_/Src/FluentAssertions/Formatting/Formatter.cs:line 106
   at FluentAssertions.Collections.GenericCollectionAssertions`3.<>c.<Satisfy>b__85_3(Predicate`1 predicate) in /_/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs:line 2832
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at FluentAssertions.Collections.GenericCollectionAssertions`3.Satisfy(IEnumerable`1 predicates, String because, Object[] becauseArgs) in /_/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs:line 2830
   at FluentAssertions.Collections.GenericCollectionAssertions`3.Satisfy(Expression`1[] predicates) in /_/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs:line 2777
   at Program.Main()
```

### Versions

* Which version of Fluent Assertions are you using? 6.1
* Which .NET runtime and version are you targeting? .NET 5

**Comment by dennisdoomen** [comment]
@vanya-lebedev Since it's a bug/missing feature in the `PredicateLambdaExpressionValueFormatter`, is this something you can help us with?

**Comment by vanya-lebedev** [comment]
Hi @dennisdoomen. Yes, absolutely. This weekend is already booked. Would next weekend be ok?

**Comment by dennisdoomen** [comment]
Awesome. Don't worry. We all do this in our private time ;-)

**Comment by jnyrup** [comment]
It of course needs to be a failing assertion to trigger the formatting logic.
```cs
var actual = new[] { 1 };
var allowed = new[] { 2 };
actual.Should().Satisfy(x => allowed.Contains(x));
```

I can prevent the exception, but the expression is then formatted as `value(System.Int32[]).Contains(x)`.
Without having looked at what we do elsewhere, it would probably be nice if it printed `allowed.Contains(x)` instead.

**Comment by vanya-lebedev** [comment]
> It of course needs to be a failing assertion to trigger the formatting logic.
> 
> ```cs
> var actual = new[] { 1 };
> var allowed = new[] { 2 };
> actual.Should().Satisfy(x => allowed.Contains(x));
> ```
> 
> I can prevent the exception, but the expression is then formatted as `value(System.Int32[]).Contains(x)`. Without having looked at what we do elsewhere, it would probably be nice if it printed `allowed.Contains(x)` instead.

Same scenario is not yet solved in e.g. Should().Contain(a => allowed.Contains(a)). Is there a solution that I can reuse? Or should we leave this out of scope of the fix?
