### ISSUE TITLE
ContainsSingle() assertion fails when collection field is tested

### ISSUE THREAD

**Issue by FLAMESpl** [fluentassertions/fluentassertions#1711]
### Description

`.ContainsSingle()` assertion fails when parsing expression tree for message output of failed assertion

### Complete minimal example reproducing the issue

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using FluentAssertions;
using Xunit;

namespace TestProject
{
    public class TestObject
    {
        public IReadOnlyCollection<string> Collection { get; set; }
    }

    public class UnitTest
    {
        [Fact]
        public void Test()
        {
            var testObjects = new[]
            {
                new TestObject
                {
                    Collection = Array.Empty<string>()
                }
            };

            var expectedCollection = new[] { "TEST" };

            testObjects.Should().ContainSingle(x => x.Collection.SequenceEqual(expectedCollection));
        }
    }
}
```

### Expected behavior:

Exception with regular message about failed assertion.

### Actual behavior:

```
TestProject.UnitTest.Test

System.ArgumentNullException: Value cannot be null. (Parameter 'body')

System.ArgumentNullException
Value cannot be null. (Parameter 'body')
   at System.Linq.Expressions.Expression.Lambda(Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda(Expression body, ParameterExpression[] parameters)
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.ConstantSubExpressionReductionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.ConstantSubExpressionReductionVisitor.Visit(Expression node)
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.ReduceConstantSubExpressions(Expression expression)
   at FluentAssertions.Formatting.PredicateLambdaExpressionValueFormatter.Format(Object value, FormattedObjectGraph formattedGraph, FormattingContext context, FormatChild formatChild)
   at FluentAssertions.Formatting.Formatter.Format(Object value, FormattedObjectGraph output, FormattingContext context, FormatChild formatChild)
   at FluentAssertions.Formatting.Formatter.ToString(Object value, FormattingOptions options)
   at FluentAssertions.Execution.MessageBuilder.<FormatArgumentPlaceholders>b__6_0(Object a)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FluentAssertions.Execution.MessageBuilder.FormatArgumentPlaceholders(String failureMessage, Object[] failureArgs)
   at FluentAssertions.Execution.MessageBuilder.Build(String message, Object[] messageArgs, String reason, ContextDataItems contextData, String identifier, String fallbackIdentifier)
   at FluentAssertions.Execution.AssertionScope.<>c__DisplayClass37_0.<FailWith>b__0()
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Collections.GenericCollectionAssertions`3.ContainSingle(Expression`1 predicate, String because, Object[] becauseArgs)
   at TestProject.UnitTest.Test() in C:\Users\lszafirski\source\repos\FluentAssertionsExpressionBugRepro\TestProject\UnitTest.cs:line 29
```

### Versions

* FluentAssertions 6.1.0
* .NET 5

### Additional information

collection field in tested class seems to be source of the issue

**Comment by jnyrup** [comment]
If you haven't already seen, the fix was released as part of [v6.2.0](https://github.com/fluentassertions/fluentassertions/releases/tag/6.2.0)
