### ISSUE TITLE
NullReferenceException in Formatter.Format

### ISSUE THREAD

**Issue by ArneMancofi** [fluentassertions/fluentassertions#2235]
### Description

We've recently started to get the following exception when running a suite of tests; when we re-run the failed tests, they succeed.
```
System.NullReferenceException
Object reference not set to an instance of an object.
   at FluentAssertions.Formatting.Formatter.<>c__DisplayClass7_0.<Format>b__0(IValueFormatter f)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at FluentAssertions.Formatting.Formatter.Format(Object value, FormattedObjectGraph output, FormattingContext context, FormatChild formatChild)
   at FluentAssertions.Formatting.Formatter.ToString(Object value, FormattingOptions options)
   at FluentAssertions.Execution.MessageBuilder.<FormatArgumentPlaceholders>b__6_0(Object a)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FluentAssertions.Execution.MessageBuilder.FormatArgumentPlaceholders(String failureMessage, Object[] failureArgs)
   at FluentAssertions.Execution.MessageBuilder.Build(String message, Object[] messageArgs, String reason, ContextDataItems contextData, String identifier, String fallbackIdentifier)
   at FluentAssertions.Execution.AssertionScope.<>c__DisplayClass38_0.<FailWith>b__0()
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.ObjectAssertions`2.Be(TSubject expected, String because, Object[] becauseArgs)
   at FluentAssertions.Equivalency.Steps.ValueTypeEquivalencyStep.Handle(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator nestedValidator)
   at FluentAssertions.Equivalency.EquivalencyValidator.TryToProveNodesAreEquivalent(Comparands comparands, IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.EquivalencyValidator.RecursivelyAssertEquality(Comparands comparands, IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.Steps.StructuralEqualityEquivalencyStep.AssertMemberEquality(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator parent, IMember selectedMember, IEquivalencyAssertionOptions options)
   at FluentAssertions.Equivalency.Steps.StructuralEqualityEquivalencyStep.Handle(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator nestedValidator)
   at FluentAssertions.Equivalency.EquivalencyValidator.TryToProveNodesAreEquivalent(Comparands comparands, IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.EquivalencyValidator.RecursivelyAssertEquality(Comparands comparands, IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.Steps.EnumerableEquivalencyValidator.TryToMatch[T](Object subject, T expectation, Int32 expectationIndex)
   at FluentAssertions.Equivalency.Steps.EnumerableEquivalencyValidator.LooselyMatchAgainst[T](IList`1 subjects, T expectation, Int32 expectationIndex)
   at FluentAssertions.Equivalency.Steps.EnumerableEquivalencyValidator.AssertElementGraphEquivalencyWithLooseOrdering[T](Object[] subjects, T[] expectations)
   at FluentAssertions.Equivalency.Steps.EnumerableEquivalencyValidator.AssertElementGraphEquivalency[T](Object[] subjects, T[] expectations, INode currentNode)
   at FluentAssertions.Equivalency.Steps.EnumerableEquivalencyValidator.Execute[T](Object[] subject, T[] expectation)
   at FluentAssertions.Equivalency.Steps.GenericEnumerableEquivalencyStep.HandleImpl[T](EnumerableEquivalencyValidator validator, Object[] subject, IEnumerable`1 expectation)
--- End of stack trace from previous location ---
   at FluentAssertions.Equivalency.Steps.GenericEnumerableEquivalencyStep.Handle(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator nestedValidator)
   at FluentAssertions.Equivalency.EquivalencyValidator.TryToProveNodesAreEquivalent(Comparands comparands, IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.EquivalencyValidator.RecursivelyAssertEquality(Comparands comparands, IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context)
   at FluentAssertions.Collections.GenericCollectionAssertions`3.BeEquivalentTo[TExpectation](IEnumerable`1 expectation, Func`2 config, String because, Object[] becauseArgs)
   at FluentAssertions.Collections.GenericCollectionAssertions`3.BeEquivalentTo[TExpectation](IEnumerable`1 expectation, String because, Object[] becauseArgs)
```
Nowhere do we call `Formatter.AddFormatter(null)`, so I don't understand why this exception is thrown?
Perhaps a null check should be added in `Formatter.Format()`?

### Reproduction Steps

```csharp
// Arrange
string input = "MyString";

// Act
char result = input[0];

// Assert
result.Should().Be('M');
```

### Expected behavior

I would not expect the formatter to cause an exception.

### Actual behavior

Sometimes, a NullReferenceException is thrown.

### Configuration

FA 6.11.0
.NET 6.0

**Comment by jnyrup** [comment]
Do you call `Formatter.RemoveFormatter` or `Formatter.AddFormatter` in any tests?
Those calls are not thread-safe as they modify the static `Formatter.CustomFormatters`.
See https://fluentassertions.com/tips/#using-global-assertionoptions on how to setup static stuff in a thread safe way.

**Comment by ArneMancofi** [comment]
> Do you call `Formatter.RemoveFormatter` or `Formatter.AddFormatter` in any tests? Those calls are not thread-safe as they modify the static `Formatter.CustomFormatters`.

Ah, that is probably the reason—thanks! 🙂👍 

It would be useful if this was clear from the documentation of formatters, though.
