### ISSUE TITLE
Struct record types generate format exception in dictionary key

### ISSUE THREAD

**Issue by Renaudyes** [fluentassertions/fluentassertions#2704]
### Description

When using a `record struct` in the generic `TKey` of a Dictionary, when an error of fluent assertion is generated, the `.ToString()` method is called which generates the following output:
`MyStruct{ MyProperty1 = "MyProperty1", MyProperty2 = "MyProeprty2", ... }`

One can see that using a `ToString()` on a record generates the characters `{` and `}` in the returned string.
The returned string is then used in turn in the `string.Format()` method but will crash because it considers `{` and `}` as parameter injection.
I mean, a message like this : `MyStruct{ MyProperty1 = "MyProperty1", MyProperty2 = "MyProeprty2", ... }` is considered as `MyStruct{ paramForFormatMethod }`.
So fluent assertion tries to inject a param in the generated string from the record struct.
(the example will help clarify)

### Reproduction Steps

```csharp
public readonly record struct MyRecordStruct
{
    public string MyProperty { get; init; }
}

[Fact]
public void myTest()
{
    var dict = new Dictionary<MyRecordStruct, MyRecordStruct>();
    var dict2 = new Dictionary<MyRecordStruct, MyRecordStruct>();

    var key = new MyRecordStruct() { MyProperty = "MyKey" };

    dict.Add(key, new MyRecordStruct());
    dict2.Add(key, new MyRecordStruct() { MyProperty = ""});

    dict2.Should().BeEquivalentTo(dict);
}
```

### Expected behavior

```
Expected property dict2[MyRecordStruct { MyProperty = MyKey }].MyProperty to be null, but found "".
```

### Actual behavior

It generates the following error message : 
```
 **WARNING** failure message 'Expected property dict2[MyRecordStruct { MyProperty = MyKey }].MyProperty to be {0}, but found {1}.' could not be formatted with string.Format
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at FluentAssertions.Execution.MessageBuilder.FormatArgumentPlaceholders(String failureMessage, Object[] failureArgs)
```

### Configuration

- FluentAssertions Version="6.12.0" 
- .NET8

**Comment by jnyrup** [comment]
Thanks for reporting this bug and providing a reproducing example.

For investigating I reduced the example to

```cs
var dict1 = new Dictionary<string, string> { ["{}"] = "" };
var dict2 = new Dictionary<string, string> { ["{}"] = null };

dict2.Should().BeEquivalentTo(dict1);
```

The problem is 

https://github.com/fluentassertions/fluentassertions/blob/a5e5a3eb917eb6ec227d0a1bdd12e90206fc5e03/Src/FluentAssertions/Equivalency/Steps/StringEqualityEquivalencyStep.cs#L79-L80

```cs
var dict1 = new Dictionary<string, object> { ["{}"] = "a" };
var dict2 = new Dictionary<string, object> { ["{}"] = new object() };

dict2.Should().BeEquivalentTo(dict1);
```

Causes a similar problem for
https://github.com/fluentassertions/fluentassertions/blob/a5e5a3eb917eb6ec227d0a1bdd12e90206fc5e03/Src/FluentAssertions/Equivalency/Steps/StringEqualityEquivalencyStep.cs#L95-L98

For both cases it _seems_ we can solve/workaround it by rewriting it into
```cs
AssertionScope.Current.AddNonReportable("ValidateAgainstNulls", currentNode.Description);
AssertionScope.Current.FailWith(
    "Expected {ValidateAgainstNulls} to be {0}{reason}, but found {1}.", expected, subject);
```

and 

```cs
AssertionScope.Current.AddNonReportable("ValidateSubjectIsString", currentNode);

return
    AssertionScope.Current
        .FailWith("Expected {ValidateSubjectIsString} to be {0}{reason}, but found {1}.",
            comparands.RuntimeType, comparands.Subject.GetType());
```

Is this misusing `AddNonReportable` @dennisdoomen?

I haven't found reproducing examples, but I suspect these four other places could suffer from the same issue.

https://github.com/fluentassertions/fluentassertions/blob/a5e5a3eb917eb6ec227d0a1bdd12e90206fc5e03/Src/FluentAssertions/Equivalency/Steps/AssertionRuleEquivalencyStep.cs#L74-L75

https://github.com/fluentassertions/fluentassertions/blob/a5e5a3eb917eb6ec227d0a1bdd12e90206fc5e03/Src/FluentAssertions/Equivalency/Steps/AssertionRuleEquivalencyStep.cs#L82-L84

https://github.com/fluentassertions/fluentassertions/blob/a5e5a3eb917eb6ec227d0a1bdd12e90206fc5e03/Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs#L36-L37

https://github.com/fluentassertions/fluentassertions/blob/a5e5a3eb917eb6ec227d0a1bdd12e90206fc5e03/Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs#L41-L43

**Comment by dennisdoomen** [comment]
Resolved in 8.1.1
