### ISSUE TITLE
BeEquivalentTo on collections presents wrong indices

### ISSUE THREAD

**Issue by quetzalcoatl** [fluentassertions/fluentassertions#2719]
### Description

Exception message throw from BeEquivalentTo for collection assertion carries good values, but wrong indices.

It is a MINOR issue, since most of the information is correct (detects different collections properly, shows compared failing value pairs correctly), but introduces some confusion. For example, in my case, the indices reported were so impossible to occur, that I thought my code-under-test was severely broken, caused "no line of code ever touches those indices"-level WTF moment, and I spent some time checking a whole lot of things in my code until I thought that hey, maybe the assertion message is just fooling me :)

### Reproduction Steps

```csharp
using System;
using FluentAssertions;
					
public class Program
{
    public static void Main()
    {
        new decimal[] { -1,0,0, -1,0,0, -1,0,0 }.Should().BeEquivalentTo(new[] { 0, 0, 0, /**/ 0, 0, 0, /**/ 0, 0, 0 });
    }
}
```

### Expected behavior

         good: exception telling me that collections differ
    very good: exception pointing out items/values at idx=0,3,6 with values -1/0

### Actual behavior

    OK exception tells me that collections differ
    XX exception confuses me by pointing out items 6,7,8 with values -1/0

raw:

```
Unhandled exception. FluentAssertions.Execution.AssertionFailedException: Expected root[6] to be 0, but found -1M.
Expected root[7] to be 0, but found -1M.
Expected root[8] to be 0, but found -1M.

With configuration:
- Use declared types and members
- Compare enums by value
- Compare tuples by their properties
- Compare anonymous types by their properties
- Compare records by their members
- Include non-browsable members
- Include all non-private properties
- Include all non-private fields
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- Without automatic conversion.

   at FluentAssertions.Execution.FallbackTestFramework.Throw(String message) in /_/Src/FluentAssertions/Execution/FallbackTestFramework.cs:line 21
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in /_/Src/FluentAssertions/Execution/TestFrameworkProvider.cs:line 40
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context) in /_/Src/FluentAssertions/Execution/CollectingAssertionStrategy.cs:line 47
   at FluentAssertions.Execution.AssertionScope.Dispose() in /_/Src/FluentAssertions/Execution/AssertionScope.cs:line 424
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context) in /_/Src/FluentAssertions/Equivalency/EquivalencyValidator.cs:line 28
   at FluentAssertions.Collections.GenericCollectionAssertions`3.BeEquivalentTo[TExpectation](IEnumerable`1 expectation, Func`2 config, String because, Object[] becauseArgs) in /_/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs:line 379
   at FluentAssertions.Collections.GenericCollectionAssertions`3.BeEquivalentTo[TExpectation](IEnumerable`1 expectation, String because, Object[] becauseArgs) in /_/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs:line 326
   at Program.Main()
```

### Regression?

I tried several future/past releases, all behave the same.
I listed them all below in 'Configuration'.

### Configuration

in my project
- dotnet 4.7.2  + Fluentassertions 6.12.0

https://dotnetfiddle.net/
- dotnet 8 + FluentAssertions 6.12.0
- dotnet 8 + FluentAssertions 7.0.0.0-alpha4
- dotnet 8 + FluentAssertions 5.10.3.0

### Other information

1) I checked `When_collections_with_duplicates_are_not_equivalent_it_should_throw` test, it works fine, reports good index. It also works fine when I switch integers to decimals. But when I replace the input/expected arrays in the test with my 9-element arrays, it reportes wrong indices just like described. It also happens regardless of using decimal arrays, or int arrays like in the test suite.

2) I noticed that the shape of the collection compared affects reported indices.
below: X bad, = good.

```
      input            x         expected     -> reported indices
-1,0,0, -1,0,0, -1,0,0 x 0,0,0, 0,0,0, 0,0,0  --> 6=,7x,8x
-1,0,0, -1,0,0, -1,0,8 x 0,0,0, 0,0,0, 0,0,8  --> 5x,6=,7x 
-1,0,0, -1,0,0, -1,7,8 x 0,0,0, 0,0,0, 0,7,8  --> 4x,5x,6= 
-1,0,0, -1,0,5, -1,7,8 x 0,0,0, 0,0,5, 0,7,8  --> 3x,4x,6= 
-1,0,0, -1,0,0, -1,7,0 x 0,0,0, 0,0,0, 0,7,0  --> 5x,6=,8x 
-1,0,0, -1,0,5, -1,7,0 x 0,0,0, 0,0,5, 0,7,0  --> 4x,6=,8x 
-1,0,0, -1,0,5, -1,0,0 x 0,0,0, 0,0,5, 0,0,0  --> 6=,7x,8x 
```

### Are you willing to help with a pull-request?

No

**Comment by quetzalcoatl** [comment]
re: "Are you willing to help with a pull-request? => No"

Actually I am, and I already published a thing or two for i.e. Moq ages ago, but I know very little about FA's internals at the moment, and my free time is scarce. I will look deeper into this at some point of time, but it's hard to estimate 'when'. There's no real sense in 'assigning' this issue to me if it takes me, say, 6-12 months. But if I find time, and find a fix, I'll post it.

**Comment by dennisdoomen** [comment]
We'll keep it around. If you find more information, post it here. We're too busy ourselves with v7 work.

**Comment by jnyrup** [comment]
Be aware that `BeEquivalentTo` per default is only strict about the ordering for byte arrays as noted in the failure message.
```
- Be strict about the order of items in byte arrays
```

If you change it to use `WithStrictOrdering()`
```cs
new decimal[] { -1,0,0, -1,0,0, -1,0,0 }.Should().BeEquivalentTo(new[] { 0, 0, 0, /**/ 0, 0, 0, /**/ 0, 0, 0 }, opt => opt.WithStrictOrdering());
```

the failure message now reports the expected indices.

```
Unhandled exception. FluentAssertions.Execution.AssertionFailedException: Expected root[0] to be 0, but found -1M.
Expected root[3] to be 0, but found -1M.
Expected root[6] to be 0, but found -1M.

With configuration:
- Use declared types and members
- Compare enums by value
- Compare tuples by their properties
- Compare anonymous types by their properties
- Compare records by their members
- Include non-browsable members
- Include all non-private properties
- Include all non-private fields
- Match member by name (or throw)
- Always be strict about the collection order
- Without automatic conversion.

   at FluentAssertions.Execution.FallbackTestFramework.Throw(String message) in /_/Src/FluentAssertions/Execution/FallbackTestFramework.cs:line 21
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in /_/Src/FluentAssertions/Execution/TestFrameworkProvider.cs:line 40
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context) in /_/Src/FluentAssertions/Execution/CollectingAssertionStrategy.cs:line 47
   at FluentAssertions.Execution.AssertionScope.Dispose() in /_/Src/FluentAssertions/Execution/AssertionScope.cs:line 424
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context) in /_/Src/FluentAssertions/Equivalency/EquivalencyValidator.cs:line 28
   at FluentAssertions.Collections.GenericCollectionAssertions`3.BeEquivalentTo[TExpectation](IEnumerable`1 expectation, Func`2 config, String because, Object[] becauseArgs) in /_/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs:line 379
   at Program.Main()
```

**Comment by quetzalcoatl** [comment]
@jnyrup :gasp: I've seen it, and I took that "be strict"+"byte arrays" as a policy simliar to others, that target specific types, like enums/values or tuples/props, and somehow, it didn't occur to me that if it is mentioned, that the default for other collection is order-agnostic match.

Now that I know, it seems obvious, why mention order for arrays at all if the 'strict order' was the default..
Thank you very much. I suppose everything's fine then!
