### ISSUE TITLE
Confusing CallStack when using Fluent Assertions

### ISSUE THREAD

**Issue by naveek** [fluentassertions/fluentassertions#512]
Using MsTest Assert I have this call stack.
   Assert.AreEqual failed. Expected:<4>. Actual:<5>. 
   at Foo.Bar() in c:\Foo\Bar.cs:line 38

Using Fluent Assertions I see this

Expected value to be 4, but found 5.
   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in z:\Builds\work\eed5b735bfe0fb8d\Shared\Execution\LateBoundTestFramework.cs:line 30
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in z:\Builds\work\eed5b735bfe0fb8d\FluentAssertions.Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] reasonArgs) in z:\Builds\work\eed5b735bfe0fb8d\FluentAssertions.Core\Numeric\NumericAssertions.cs:line 49
   at Foo.Bar() in c:\Foo\Bar.cs:line 36

Is there a way where we don't get the complete call stack that includes FluentAssertions since it is confusing compared to simple MSTest Asserts?

**Comment by naveek** [comment]
I wonder https://msdn.microsoft.com/en-us/library/system.diagnostics.debuggernonusercodeattribute.aspx debuggernonusercodeattribute on FluentAssertion classes will help with that.

**Comment by dennisdoomen** [comment]
Which version of Visual Studio are you using? And what assembly is the [TestMethod] coming from? It's almost as if FA is throwing the wrong exception type.

**Comment by naveek** [comment]
Thanks Dennis for getting back.

We are using VS 2013.
This is a Unit Test assembly that we have written that uses MSTest.

To test this, I just ran

            5.Should().Be(6);

Output in VS Unit Test Session Window.

   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in z:\Builds\work\eed5b735bfe0fb8d\Shared\Execution\LateBoundTestFramework.cs: line 30   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in z:\Builds\work\eed5b735bfe0fb8d\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs: line 43   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in z:\Builds\work\eed5b735bfe0fb8d\FluentAssertions.Core\Execution\DefaultAssertionStrategy.cs: line 26   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in z:\Builds\work\eed5b735bfe0fb8d\FluentAssertions.Core\Execution\AssertionScope.cs: line 200   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] reasonArgs) in z:\Builds\work\eed5b735bfe0fb8d\FluentAssertions.Core\Numeric\NumericAssertions.cs: line 44   at Foo.Bar() in Foo.cs: line 14

            Assert.Equals(5, 6);

Assert.AreEqual failed. Expected:<5>. Actual:<6>.
   at Foo.Bar() in Foo.cs: line 14

Regards,
Naveen

If you want to go quickly, go alone. If you want to go far, go together.

**Comment by dennisdoomen** [comment]
But if you attach the debugger, what is the fully-qualified namespace (and assembly) of the exception type. The reason I ask is because FA should detect the framework and throw the right exception.

**Comment by dennisdoomen** [comment]
Did a bit of investigation and concluded that the current behavior is very difficult to fix. Basically you would need to back into the exception instance and overwrite the stacktrace.

**Comment by dennisdoomen** [comment]
For xUnit, it looks like we can just throw a sub-class of `xUnitException` and override its `ToString`. However, we don't have a direct dependency on xUnit, so that might be a bit tricky. We can still decide to use Reflection to override the stack trace. Another thing to try is to throw our own exception and see how that is handled by xUnit.

**Comment by jnyrup** [comment]
I've tried poking around with this and even through I set a stack trace on the exception with reflection, it seems the `throw` keyword overwrites it again.

Another approach could be to wrap calls to throwing methods with `RewriteStackTrace` to throw away parts of the stack trace.

```cs
public Continuation FailWith(string message)
{
    return RewriteStackTrace(() => FailWith(() => new FailReason(message, new object[0])));
}

public Continuation FailWith(string message, params object[] args)
{
    return RewriteStackTrace(() => FailWith(() => new FailReason(message, args)));
}

public Continuation FailWith(string message, params Func<object>[] argProviders)
{
    return RewriteStackTrace(() => FailWith(() => new FailReason(message,
        argProviders.Select(a => a()).ToArray())));
}

[MethodImpl(MethodImplOptions.AggressiveInlining)]
internal static T RewriteStackTrace<T>(Func<T> act)
{
    try
    {
        return act();
    }
    catch (Exception ex)
    {
        throw ex;
    }
}
```

That reduces the stack trace for 
```cs
5.Should().Be(6);
```
from
```
Stack Trace: 
    XUnit2TestFramework.Throw(String message) line 35
    TestFrameworkProvider.Throw(String message) line 32
    DefaultAssertionStrategy.HandleFailure(String message) line 25
    AssertionScope.FailWith(Func`1 failReasonFunc) line 257
    AssertionScope.FailWith(Func`1 failReasonFunc) line 229
    AssertionScope.FailWith(String message, Object[] args) line 283
    NumericAssertions`2.Be(T expected, String because, Object[] becauseArgs) line 59
    DataSetEquivalencySpecs.Lollostein() line 294
```
to
```
Stack Trace: 
    AssertionScope.FailWith(String message, Object[] args) line 284
    NumericAssertions`2.Be(T expected, String because, Object[] becauseArgs) line 59
    DataSetEquivalencySpecs.Lollostein() line 294
```

**Comment by dennisdoomen** [comment]
If that works on all platforms, then I would also remove the `AssertionScope.FailWith`

**Comment by GeeWee** [comment]
It'd be super cool to have this. I'm in the process of comparing call stacks for e.g. xUnit's assert which just fails directly on the line (one line stacktrace looking like:
```
     at MyProject.FluentAssertionsTest.simpletestxunit() in /home/geewee/Programming/BlogProjects/BlogProject/FluentAssertionsTest.cs:line 25
```
whereas the FluentAssertion one is quite a bit longer and more noisy.

**Comment by jnyrup** [comment]
> If that works on all platforms, then I would also remove the `AssertionScope.FailWith`

There should be nothing platform specific about catching an exception and throwing the catched exception. 
I did not find a way to also remove  `FailWith` from the stack trace.

Would it make sense for end-users to have a global flag to disable the stack rewriting?

**Comment by dennisdoomen** [comment]
Why would you do that?

**Comment by jnyrup** [comment]
Except for debugging into FA I don't see any case, that's why I'm asking :)

**Comment by dennisdoomen** [comment]
Well yes, I guess we should ensure a `debug` build of FA should not touch the stack trace.

**Comment by darcythomas** [comment]
A possible way to implement this would be to add the [`StackTraceHiddenAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.stacktracehiddenattribute?view=net-8.0)

**Comment by dennisdoomen** [comment]
Oh wow, I didn't know about that one. Great tip @darcythomas

**Comment by dennisdoomen** [comment]
Works great on .NET 6 or later. Before that, it's `internal`
