### ISSUE TITLE
How to hide stacktrace when a test fails

### ISSUE THREAD

**Issue by davidkeaveny** [fluentassertions/fluentassertions#539]
I'm running FluentAssertions 4.18.0 with NUnit 3.6.0 on TeamCity 10.0.4, and when a test fails, I'm seeing the stacktrace for the assertion library:

```
NUnit Console Runner 3.6.0 
Copyright (C) 2016 Charlie Poole
Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 4.0.30319.36373
Test Files
    Api.Client.Specs.dll
Errors and Failures
1) Failed : Api.Client.Tests.Countries.WhenGettingCountryById.TheContentShouldDeserialiseToTheExpectedType
Expected object not to be <null>.
at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
at FluentAssertions.Primitives.ReferenceTypeAssertions`2.NotBeNull(String because, Object[] becauseArgs)
2) Failed : Api.Client.Tests.Countries.WhenGettingCountryById.TheContentShouldNotBeEmpty
Expected a value greater than 0L, but found 0L.
at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
at FluentAssertions.Numeric.NumericAssertions`1.BeGreaterThan(T expected, String because, Object[] becauseArgs)
at Api.Client.Tests.GetOne`2.TheContentShouldNotBeEmpty() in d:\BuildAgent\buildAgent\work\3f796dfb5b55ed2b\Api.Client.Specs\GetOne.cs:line 53
3) Failed : Api.Client.Tests.Countries.WhenGettingCountryById.TheHttpStatusShouldBe200
Expected object to be OK, but found NotFound.
at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
at FluentAssertions.Primitives.ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)
at Api.Client.Tests.GetOne`2.TheHttpStatusShouldBe200() in d:\BuildAgent\buildAgent\work\3f796dfb5b55ed2b\Api.Client.Specs\GetOne.cs:line 47
```

The stacktrace is offering no value at all (my tests are one liners, so it if fails, it's pretty obvious where) and all I really need to see is the actual message, which is rather hard to see with all that extra cruft in there. No wonder my server logs are ballooning...

I suppose this is similar to #512 but here I just want to see the message and nothing else.

**Comment by dennisdoomen** [comment]
Is FA correctly throwing an NUnit-specific exception type?

**Comment by davidkeaveny** [comment]
It is throwing an `NUnit.Framework.AssertionException`, if that's what you mean. I just would expect to see the error message, but not the call stack that led to the test failure.

**Comment by dennisdoomen** [comment]
Then the only way to fix this to hack into the exception itself and remove parts of the stack trace.
