### ISSUE TITLE
Problems upgrading xUnit dependency

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#720]
I'm trying to upgrade xUnit from the current 2.3.0-beta5 to some stable version.

Upgrading to 2.3.0-rc2, 2.3.0 or 2.3.1 causes:
 *only* `FluentAssertions.Specs.FormatterSpecs.When_a_custom_formatter_exists_in_any_loaded_assembly_it_should_override_the_default_formatters` 
 to fail for *only* `NetCore.Specs`
 *only* when running build.ps1

I made the tests run by modifying the Cake script to use `DotNetCoreTest` instead of `DotNetCoreTool(path, "xunit")`, which should be the Cake equivalent of `dotnet test` and `dotnet xunit`.

The results when using `dotnet xunit` and `dotnet test` directly:

```PS
PS C:\git\fluentassertions\Tests\NetCore.Specs> dotnet xunit -method FluentAssertions.Specs.FormatterSpecs.When_a_custom_formatter_exists_in_any_loaded_assembly_it_should_override_the_default_formatters
Detecting target frameworks in NetCore.Specs.csproj...
Building for framework netcoreapp1.1...
  FluentAssertions -> C:\git\fluentassertions\Src\FluentAssertions\bin\Debug\netstandard1.6\FluentAssertions.dll
  NetCore.Specs -> C:\git\fluentassertions\Tests\NetCore.Specs\bin\Debug\netcoreapp1.1\FluentAssertions.NetCore.Specs.dll
Running .NET Core 1.1.2 tests for framework netcoreapp1.1...
xUnit.net Console Runner (32-bit .NET Core 4.6.25211.01)
  Discovering: FluentAssertions.NetCore.Specs
  Discovered:  FluentAssertions.NetCore.Specs
  Starting:    FluentAssertions.NetCore.Specs
    FluentAssertions.Specs.FormatterSpecs.When_a_custom_formatter_exists_in_any_loaded_assembly_it_should_override_the_default_formatters [FAIL]
      Expected string to be
      "Property = SomeValue" with a length of 20 because it should use my custom formatter, but
      "The value of my property is SomeValue" has a length of 37.
      Stack Trace:
        C:\git\fluentassertions\Src\FluentAssertions\Execution\XUnit2TestFramework.cs(35,0): at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
        C:\git\fluentassertions\Src\FluentAssertions\Execution\TestFrameworkProvider.cs(40,0): at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
        C:\git\fluentassertions\Src\FluentAssertions\Execution\DefaultAssertionStrategy.cs(25,0): at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
        C:\git\fluentassertions\Src\FluentAssertions\Execution\AssertionScope.cs(197,0): at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
        C:\git\fluentassertions\Src\FluentAssertions\Primitives\StringEqualityValidator.cs(30,0): at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences()
        C:\git\fluentassertions\Src\FluentAssertions\Primitives\StringValidator.cs(41,0): at FluentAssertions.Primitives.StringValidator.Validate()
        C:\git\fluentassertions\Src\FluentAssertions\Primitives\StringAssertions.cs(39,0): at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs)
        C:\git\fluentassertions\Tests\Shared.Specs\FormatterSpecs.cs(749,0): at FluentAssertions.Specs.FormatterSpecs.When_a_custom_formatter_exists_in_any_loaded_assembly_it_should_override_the_default_formatters()
  Finished:    FluentAssertions.NetCore.Specs
=== TEST EXECUTION SUMMARY ===
   FluentAssertions.NetCore.Specs  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.231s
```

```PS
PS C:\git\fluentassertions\Tests\NetCore.Specs> dotnet test --filter When_a_custom_formatter_exists_in_any_loaded_assembly_it_should_override_the_default_formatters
Build started, please wait...
Build completed.

Test run for C:\git\fluentassertions\Tests\NetCore.Specs\bin\Debug\netcoreapp1.1\FluentAssertions.NetCore.Specs.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.8307853]   Discovering: FluentAssertions.NetCore.Specs
[xUnit.net 00:00:01.2452271]   Discovered:  FluentAssertions.NetCore.Specs
[xUnit.net 00:00:01.2565606]   Starting:    FluentAssertions.NetCore.Specs
[xUnit.net 00:00:01.4255919]   Finished:    FluentAssertions.NetCore.Specs

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.2004 Seconds
```

To me this indicates that either `dotnet-xunit`/`xunit.runner.console` broke between `2.3.0-beta5` and `2.3.0-rc2` or that we are doing something wrong.

Before opening an issue on the xUnit issue tracker, maybe someone in here has more knowledge than me in this area?

Here's a repo:
https://github.com/jnyrup/fluentassertions/tree/xunit-issue

**Comment by dennisdoomen** [comment]
That specific unit test is using assembly scanning to find a custom value formatter. Maybe something changed in the way Xunit deals with AppDomains again.

**Comment by jnyrup** [comment]
`NetStandardReflector.GetAllTypesFromAppDomain` behaves different. 
I'll investigate

**Comment by jnyrup** [comment]
Note: The problem has disappeared with `xUnit 2.4.0-beta1-build3896` which was triggered by https://github.com/xunit/xunit/commit/8d0cdc1cf585f5cf285d221e0c8ff793e6aeea30

**Comment by dennisdoomen** [comment]
So we can close this now?

**Comment by jnyrup** [comment]
In the current state, if using Fluent Assertions and `ValueFormatterDetectionMode` one needs to use xUnit at most 2.3.0-beta5 or at least xUnit 2.4.0-beta1-build3896.

If that is okay with you, we should just note it somewhere in the docs.

**Comment by dennisdoomen** [comment]
So 2.3.0 and 2.3.1 are fine as well?

**Comment by jnyrup** [comment]
No.
It works in 2.3.0-beta5 which we currently use. 
It then broke in 2.3.0-rc1 and wasn't fixed until 2.4.0-beta1-build3896.

**Comment by dennisdoomen** [comment]
Might be related to `AppDomain` loading. 

I think we should add this to https://github.com/fluentassertions/fluentassertions/blob/release-5.0/docs/extensibility.md

**Comment by jnyrup** [comment]
I think you're right about the `AppDomain` think.
It stopped working somewhere [here](https://github.com/xunit/xunit/compare/2.3-beta5...2.3-rc2).

I can try to bisect the particular commit, if that is of any help?
