### ISSUE TITLE
ShouldBeEquivalentTo() fails on netcoreapp2.0 for deserialized nested dictionaries

### ISSUE THREAD

**Issue by danjagnow** [fluentassertions/fluentassertions#741]
The following test passes when compiled for **net462** but fails for **netcoreapp2.0**:

``` cs
const string json = @"{
    ""NestedDictionary"": {
        ""StringProperty"": ""string"",
        ""IntProperty"": 123
    }
}";
            
var expectedResult = new Dictionary<string, object>
{
    ["NestedDictionary"] = new Dictionary<string, object>
    {
        ["StringProperty"] = "string",
        ["IntProperty"] = 123
    }
};

var result = JsonConvert.DeserializeObject<Dictionary<string, object>>(json);
result.ShouldBeEquivalentTo(expectedResult);
```

Tested with **FluentAssertions** 4.19.4 and **Newtonsoft.Json** 10.0.3.  Output from the failed test looks like this:

```
Expected pair[NestedDictionary][StringProperty] to be "string", but found {empty}.
Expected pair[NestedDictionary][IntProperty] to be 123, but found {empty}.

With configuration:
- Use declared types and members
- Compare enums by value
- Match member by name (or throw)
- Be strict about the order of items in byte arrays

   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context)
   at FluentAssertions.AssertionExtensions.ShouldBeEquivalentTo[T](T subject, Object expectation, String because, Object[] becauseArgs)
   at FluentSandbox.UnitTest1.WorksOnNetFrameworkButFailsOnCore() in C:\Dev\FluentSandbox\UnitTest1.cs:line 30
```

I've added a minimal project for reproducing the issue at https://github.com/danjagnow/FluentSandbox.  Just pull the repository and run `dotnet test` from the root.

**Comment by dennisdoomen** [comment]
Thanks for reporting this. Could you please retest this with 5.0 RC2? We're very close to releasing that one.

**Comment by danjagnow** [comment]
Sure.  I added a **5.0-RC2** branch to the repository that sets that up.  It was necessary to change the calls from `ShouldBeEquivalentTo()` to `Should().BeEquivalentTo()` to get that to compile due to the expected breaking changes with 5.0.  The behavior is different.  The `WorksOnBoth` unit test in the repository continues to pass on both **net462** and **netcoreapp2.0**.  The `WorksOnNetFrameworkButFailsOnCore` unit test now fails on both target frameworks, but with different failure modes.  So I guess the test needs a new name.  :-)

On **net462**, it does this:
```

System.ArgumentException : Argument types do not match
   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
   at FluentAssertions.Equivalency.GenericEnumerableEquivalencyStep.ToArray(Object value, Type typeOfEnumeration)
   at FluentAssertions.Equivalency.GenericEnumerableEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.GenericDictionaryEquivalencyStep.AssertDictionaryEquivalence[TSubjectKey,TSubjectValue,TExpectedKey,TExpectedValue](EquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config, IDictionary`2 subject, IDictionary`2 expectation)
   at lambda_method(Closure )
```

On **netcoreapp2.0**, it does this:
```
Expected pair[NestedDictionary][StringProperty] to be "string", but found {empty}.
Expected pair[NestedDictionary][IntProperty] to be 123, but found {empty}.

With configuration:
- Use declared types and members
- Compare enums by value
- Match member by name (or throw)
- Be strict about the order of items in byte arrays

   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context)
   at FluentAssertions.AssertionExtensions.ShouldBeEquivalentTo[T](T subject, Object expectation, String because, Object[] becauseArgs)
   at FluentSandbox.UnitTest1.WorksOnNetFrameworkButFailsOnCore() in C:\Dev\FluentSandbox\UnitTest1.cs:line 30
```

**Comment by danjagnow** [comment]
To be clear, it's quite possible that this test *should* fail.  The types it's comparing are structurally similar but different.  But I would love it if the behavior was the same regardless of whether it's running on .NET Framework or .NET Core.

**Comment by dennisdoomen** [comment]
I agree. I'll investigate.

**Comment by dennisdoomen** [comment]
After debugging, it looks like `JsonConvert` returns a dictionary which single item has key `NestedDictionary` and a value of type `JObject`. That's obviosuly never going to work.

**Comment by dennisdoomen** [comment]
After merging #746, the result will be:

```
Did not expect any exception, but found Xunit.Sdk.XunitException with message "Expected pair[NestedDictionary][StringProperty] to be System.String, but found Newtonsoft.Json.Linq.JValue.
```
