### ISSUE TITLE
FormatException when a bad string is included in the 'because' clause of a failed assertion

### ISSUE THREAD

**Issue by bernard-chen** [fluentassertions/fluentassertions#756]
When a particular string is included in the because clause of a failed assertion, it causes the assertion to throw a FormatException instead of an AssertionFailedException. This string comes from the big list of naughty strings (https://github.com/minimaxir/big-list-of-naughty-strings) and corresponds to "<>?:\"{}|_+".

This problem can be reproduced with the following .NET Core 2.0 console app with a reference to the 5.0 version of FluentAssertions:

```
using FluentAssertions;
using FluentAssertions.Execution;

namespace BadStringForFluentAssertions
{
    class Program
    {
        static void Main(string[] args)
        {
            // When decoded, this string is "<>?:\"{}|_+"
            const string base64Encoded = "PD4/OiJ7fXxfKw==";
            var troublesomeString = System.Text.Encoding.UTF8.GetString(System.Convert.FromBase64String(base64Encoded));

            // This assertion throws a format exception rather than the correct AssertionFailedException
            System.Action a = () =>
                troublesomeString.Should().Be("foo", $"{troublesomeString} causes trouble in the 'because' clause");

            a.Should().Throw<AssertionFailedException>();
        }
    }
}

```

The actual error I get is:

```
FluentAssertions.Execution.AssertionFailedException
  HResult=0x80131500
  Message=Expected a <FluentAssertions.Execution.AssertionFailedException> to be thrown, but found a <System.FormatException>: System.FormatException with message "Input string was not in a correct format."
     at System.Text.StringBuilder.FormatError()
     at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
     at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
     at System.String.Format(String format, Object[] args)
     at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 208
     at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences() in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\StringEqualityValidator.cs:line 30
     at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\StringValidator.cs:line 41
     at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\StringAssertions.cs:line 41
     at BadStringForFluentAssertions.Program.<>c__DisplayClass0_0.<Main>b__0() in d:\dev\BadStringForFluentAssertions\BadStringForFluentAssertions\Program.cs:line 16
     at FluentAssertions.Specialized.ActionAssertions.InvokeSubjectWithInterception() in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Specialized\ActionAssertions.cs:line 118
.
  Source=FluentAssertions
  StackTrace:
   at FluentAssertions.Execution.FallbackTestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\FallbackTestFramework.cs:line 21
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 215
   at FluentAssertions.Specialized.ActionAssertions.Throw[TException](String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Specialized\ActionAssertions.cs:line 60
   at BadStringForFluentAssertions.Program.Main(String[] args) in d:\dev\BadStringForFluentAssertions\BadStringForFluentAssertions\Program.cs:line 18

```

**Comment by bernard-chen** [comment]
I think this comes down to string.Format not liking unescaped braces being passed in. One option might be to replace empty braces (or braces with only whitespace between) with the equivalent text but with the braces doubled.

**Comment by dennisdoomen** [comment]
Thanks for reporting this. Out of curiosity, is this just a made-up example, or are you actually trying to include the expectation in the _because_ parameter?

**Comment by bernard-chen** [comment]
I was iterating over all the strings in the list of naughty strings that I included in the original report and seeing if any of them caused problems with a function I was testing. Because I was feeding each of them into the function, I also needed to know which of them was failing, so I included the string in the "because" parameter. When I did this, I encountered the format exception rather than the assertion exception. It prevented me from knowing which string was causing trouble.

I also encountered this problem even though the assertion was succeeding when I was using FluentAssertions 4.x, but it looks like we format the because clause only in the case of a failure in 5.x.

Something like this change to BecauseOf would fix the issue:

```
        public AssertionScope BecauseOf(string because, params object[] becauseArgs)
        {
            const string pattern = @"\{(\s*)\}";
            const string replacement = @"{{$1}}";
            System.Text.RegularExpressions.Regex regex = new System.Text.RegularExpressions.Regex(pattern);

            reason = () => string.Format(regex.Replace(because ?? "", replacement), becauseArgs ?? new object[0]);
            return this;
        }
```

I don't know if we would want to run the regex every time though. It should be possible to do some kind of cheaper check before applying the regex.

Here was the test I created to reproduce the problem within the FluentAssertions code.

```
        [Fact]
        public void When_empty_braces_are_used_in_the_because_parameter_it_should_should_render_them_correctly()
        {
            //-----------------------------------------------------------------------------------------------------------
            // Act
            //-----------------------------------------------------------------------------------------------------------
            Action act = () => 1.Should().Be(2, "can't use curly braces in because: {}");

            //-----------------------------------------------------------------------------------------------------------
            // Assert
            //-----------------------------------------------------------------------------------------------------------
            act.Should().Throw<XunitException>()
                .WithMessage("*because can't use curly braces in because:*");
        }
```

**Comment by dennisdoomen** [comment]
Thanks for that solution. I have to say it is kind of an edge case, but we do not encode the _because_ string. And you're right. In 5.0, we don't do any formatting until the assertion really fails.

**Comment by dennisdoomen** [comment]
BTW, if you want, you can become a contributor ;-)

**Comment by bernard-chen** [comment]
I agree it's an edge case.

I've never made a contribution to an open source project. I was reading up on how to create a PR for this project and I could probably use some guidance on how to create one for this change. Would I fork this project and create a PR from that, or is the process simpler if I become a contributor? Also, I did not see the develop branch mentioned in the CONTRIBUTING.md.

**Comment by dennisdoomen** [comment]
Yep, check out https://help.github.com/articles/fork-a-repo/
