### ISSUE TITLE
simple array comparison in BeEquivalentTo no longer works.

### ISSUE THREAD

**Issue by jimmymain** [fluentassertions/fluentassertions#794]
Given the following application, using FluentAssertions version (5.1.2)

``` c#
public class Program
{
	public static void Main()
	{
		var a = new SampleTestMessageHeader();
		var b = new SampleTestMessageHeader();
		a.Should().BeEquivalentTo(b); // works just fine.

		a.CHAR = "AB".ToCharArray();
		b.CHAR = "AB".ToCharArray();

		a.Should().BeEquivalentTo(b); // throws exception.

	}
}

public struct SampleTestMessageHeader
{
	public char[] CHAR;
	public SampleTestMessageHeader(int size)
	{
		this.CHAR = "XMMA".ToCharArray();
	}
}
```

The array comparison throws an exception when it probably should not.

**Comment by dennisdoomen** [comment]
Thanks for reporting. I just tried this on the _develop_ branch and it succeeds as expected. Which version are you using?

**Comment by jimmymain** [comment]
Hi,
Just checked it again, I am using 5.1.2, exception is being thrown as per my comment.

**Comment by jnyrup** [comment]
It throws for me both in a clean project using 5.1.2 and as a test in the master branch.

**Comment by jnyrup** [comment]
The test example needs a little tuning.
We need to call the explicit constructor and not the default parameterless.

```
var a = new SampleTestMessageHeader(0);
var b = new SampleTestMessageHeader(0);
a.Should().BeEquivalentTo(b); // fails
```

**Comment by jimmymain** [comment]
the most technically correct way to construct a `struct` with default arguments is this:

``` c#
var a = default(SampleTestMessageHeader);
var b = default(SampleTestMessageHeader);
a.Should().BeEquivalentTo(b); // works just fine.
```

**Comment by dennisdoomen** [comment]
@jnyrup does it also fail on the current _master_ branch (which is a bit ahead of 5.1.2)?

**Comment by jnyrup** [comment]
@dennisdoomen just tried pulling newest master and it still fails for me.

```c#
public struct SampleTestMessageHeader
        {
            public char[] CHAR;
            public SampleTestMessageHeader(int size)
            {
                this.CHAR = "XMMA".ToCharArray();
            }
        }

        [Fact]
        public void lollostein()
        {
            var a = new SampleTestMessageHeader(0);
            var b = new SampleTestMessageHeader(0);
            a.Should().BeEquivalentTo(b); // fails
        }
```

```
Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\git\fluentassertions\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\git\fluentassertions\Src\FluentAssertions\Execution\TestFrameworkProvider.cs:line 40
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context) in C:\git\fluentassertions\Src\FluentAssertions\Execution\CollectingAssertionStrategy.cs:line 50
   at FluentAssertions.Execution.AssertionScope.Dispose() in C:\git\fluentassertions\Src\FluentAssertions\Execution\AssertionScope.cs:line 301
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\git\fluentassertions\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 41
   at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs) in C:\git\fluentassertions\Src\FluentAssertions\Primitives\ObjectAssertions.cs:line 127
   at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, String because, Object[] becauseArgs) in C:\git\fluentassertions\Src\FluentAssertions\Primitives\ObjectAssertions.cs:line 86
   at FluentAssertions.Specs.TypeAssertionSpecs.lollostein() in C:\git\fluentassertions\Tests\Shared.Specs\TypeAssertionSpecs.cs:line 29
Result Message:	
Expected object to be 

FluentAssertions.Specs.TypeAssertionSpecs+SampleTestMessageHeader
{
   CHAR = {X, M, M, A}
}, but found 

FluentAssertions.Specs.TypeAssertionSpecs+SampleTestMessageHeader
{
   CHAR = {X, M, M, A}
}.

With configuration:
- Use declared types and members
- Compare enums by value
- Match member by name (or throw)
- Without automatic conversion.
- Be strict about the order of items in byte arrays
```

**Comment by dennisdoomen** [comment]
Ah, it's a struct! Structs override `Equals` and thus will be treated as having value semantics. See also http://fluentassertions.com/documentation.html#value-types
