### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by PavelA85** [fluentassertions/fluentassertions#829]
Version 5.2.0
Not sure what I am doing wrong but I get NRE here:

`
revisions.Single().Should().BeEquivalentTo(expected, opt => opt
.Excluding(x => x.Id)
.Excluding(x => x.SecretKey)
.Excluding(x => x.EmailMessage));`

`System.NullReferenceException
Object reference not set to an instance of an object.
   at FluentAssertions.Equivalency.AssertionContext`1.CreateFromEquivalencyValidationContext(IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.AssertionRule`1.AssertEquality(IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.AssertionRuleEquivalencyStepAdapter.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config)
   at FluentAssertions.Equivalency.RunAllUserStepsEquivalencyStep.<>c__DisplayClass1_0.<Handle>b__1(IEquivalencyStep step)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at FluentAssertions.Equivalency.RunAllUserStepsEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.StructuralEqualityEquivalencyStep.AssertMemberEquality(IEquivalencyValidationContext context, IEquivalencyValidator parent, SelectedMemberInfo selectedMemberInfo, IEquivalencyAssertionOptions config)
   at FluentAssertions.Equivalency.StructuralEqualityEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context)
   at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs)
   at _3Logger.Backend.AcceptanceTests.Services.RevisionRemindSenderServiceTests.<RevisionAreSent>d__0.MoveNext() in C:\AcceptanceTests\Services\RevisionRemindSenderServiceTests.cs:line 58
`

**Comment by PavelA85** [comment]
When the assertion fails, I get an error.
When assertion passed I get NRE :)
hope this helps
class is nothing special:

    public class UserRevisionRendition
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public DateTime IssueDate { get; set; }
        public Guid SecretKey { get; set; }
        public DateTime? EmailSentOn { get; set; }
        public string EmailSubject { get; set; }
        public string EmailMessage { get; set; }
        public string EmailAddress { get; set; }
        public Guid AccountId { get; set; }
        public string TenantId { get; set; }
        public string EmailError { get; set; }
        public DateTime? FirstReminderSentOn { get; set; }
        public string FirstReminderError { get; set; }
        public DateTime? SecondReminderSentOn { get; set; }
        public string SecondReminderError { get; set; }
    }

**Comment by PavelA85** [comment]
5.1 throws.
5.0 throws.
4.19.4 do not throws.

**Comment by jnyrup** [comment]
Can  you provide an example that throws?

Are you by any change using `AssertionOptions.AssertEquivalencyUsing`? 
That was the problem in #778 .

**Comment by TheAifam5** [comment]
Other example:
```
result.Value
        .Should ()
          .NotBeNull ()
      .And
        .BeOfType<TimeEntryModel> ()
      .And
        .As<TimeEntryModel> () // returns null
        .Id.Should ()
          .NotBeEmpty ();
```
The type of `result.Value` is `TimeEntryModel`.

**Comment by jnyrup** [comment]
@TheAifam5 Your example suffers an unrelated problem. 
Please open a separate issue or join the [Slack channel](https://fluentassertionsslack.herokuapp.com/) and I'll explain it.

**Comment by jnyrup** [comment]
Closing due to inactivity.
@PavelA85 Please re-open if it's still a problem and you can provide a complete minimal example that we can run.
