### ISSUE TITLE
FluentAssertions.CallerIdentifier.ExtractVariableNameFrom - ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by kierenj** [fluentassertions/fluentassertions#844]
NuGet version - 5.3.0

Exception:

````
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FluentAssertions.CallerIdentifier.ExtractVariableNameFrom(StackFrame frame) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\CallerIdentifier.cs:line 69
   at FluentAssertions.CallerIdentifier.DetermineCallerIdentity() in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\CallerIdentifier.cs:line 31
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 218
   at FluentAssertions.Collections.CollectionAssertions`2.ContainInOrder(IEnumerable expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\CollectionAssertions.cs:line 631
````

Test code:

````c#
        [Fact]
        public void ContainInOrderIssue()
        {
            var list = new List<(string, object)>();

            list.Add(("one", new List<Type>()));
            list.Add(("two", null));
            list.Add(("test1", null));
            list.Add(("test2", null));
            list.Add(("test3", null));

            list.AsReadOnly().Should().ContainInOrder(
                ((string, object))("test1", null),
                ((string, object))("texst2", null), // runs fine when this is "test2"
                ((string, object))("test3", null)
            );
        }
````

**Comment by kierenj** [comment]
(Incidentally: I'm trying to recreate a minimal repro for a ContainInOrder failing with a list of value tuples. However, the test passes, so I'll keep trying - that's a separate issue)

**Comment by jnyrup** [comment]
Thanks for reporting this.

I can't reproduce the exception from your example.
Does this fail *every* time for you? 

While we haven't traced the exact cause, we have a "fix" in #841, which will be included in the next release.
