### ISSUE TITLE
Should().ContainInOrder() - false negative?

### ISSUE THREAD

**Issue by kierenj** [fluentassertions/fluentassertions#845]
Version: 5.3.0

Exception / failure message:

```c#
Xunit.Sdk.XunitException: Expected collection {(KnownRoleTypes, System.Collections.Generic.List`1[System.Type]), (HostResultRun, ), (test1, ), (test2, ), (test3, )} to contain items {(test1, ), (test2, ), (test3, )} in order, but (test1, ) (index 0) did not appear (in the right order).
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 225
   at FluentAssertions.Collections.CollectionAssertions`2.ContainInOrder(IEnumerable expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\CollectionAssertions.cs:line 631
```

Code:

```c#
results.Events.Should().ContainInOrder(
    new Tuple<string, object>("test1", null),
    new Tuple<string, object>("test2", null),
    new Tuple<string, object>("test3", null)
);
```

The exception seems to contradict itself - the collection does have those items?

**Comment by jnyrup** [comment]
Please provide a complete example.
It makes it harder to debug, when one has to guess the type and content of `result.events`.

**Comment by samiarahman** [comment]
We noticed the same issue. We only see it when we run the test in our pipelines

**Comment by jnyrup** [comment]
Closing due to inactivity.
If you've got a *complete minimal example*, please re-open.

**Comment by luiscantero** [comment]
I ran into a similar problem and found this issue. To repro in 6.1.0 do this:
```
var results = new List<object>
{
    new Tuple<object, object>("test1", null),
    new Tuple<object, object>("test2", null),
    new Tuple<object, object>("test3", null),
};

results.Should().ContainInOrder(
    new Tuple<string, object>("test1", null),
    new Tuple<string, object>("test2", null),
    new Tuple<string, object>("test3", null)
);
```

**Comment by dennisdoomen** [comment]
I can reproduce that last example.

**Comment by maw136** [comment]
Reproducable in our code as well - with different by comparable code. The item is a class that has immutable properties and doesn't implement IEquatable<> nor override Equals().
When switched to readonly record class () the issue disappears.

**Comment by jnyrup** [comment]
From my perspective, yes.
I see no bugs here.
