### ISSUE TITLE
Race condition in SelfReferenceEquivalencyAssertionOptions.GetEqualityStrategy

### ISSUE THREAD

**Issue by skolima** [fluentassertions/fluentassertions#862]
### Description

Race condition in SelfReferenceEquivalencyAssertionOptions.GetEqualityStrategy

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.

```csharp
// Arrange
string input = "MyString";

// Act
char result = input[0];

// Assert
result.Should().Be('M');
```

### Expected behavior:

No exception, assertions work.

### Actual behavior:

One of two exceptions is possible:
```
System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at FluentAssertions.Equivalency.SelfReferenceEquivalencyAssertionOptions`1.FluentAssertions.Equivalency.IEquivalencyAssertionOptions.GetEqualityStrategy(Type type) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\SelfReferenceEquivalencyAssertionOptions.cs:line 175
   at FluentAssertions.Equivalency.SelfReferenceEquivalencyAssertionOptions`1.FluentAssertions.Equivalency.IEquivalencyAssertionOptions.GetEqualityStrategy(Type type) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\SelfReferenceEquivalencyAssertionOptions.cs:line 175
   at FluentAssertions.Equivalency.ValueTypeEquivalencyStep.CanHandle(IEquivalencyValidationContext context, IEquivalencyAssertionOptions config) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\ValueTypeEquivalencyStep.cs:line 17
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 83
   at FluentAssertions.Equivalency.StructuralEqualityEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\StructuralEqualityEquivalencyStep.cs:line 46
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 85
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 38
   at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\ObjectAssertions.cs:line 87
   at 
```

(Rarer)
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at FluentAssertions.Equivalency.SelfReferenceEquivalencyAssertionOptions`1.FluentAssertions.Equivalency.IEquivalencyAssertionOptions.GetEqualityStrategy(Type type) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\SelfReferenceEquivalencyAssertionOptions.cs:line 182
   at FluentAssertions.Equivalency.SelfReferenceEquivalencyAssertionOptions`1.FluentAssertions.Equivalency.IEquivalencyAssertionOptions.GetEqualityStrategy(Type type) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\SelfReferenceEquivalencyAssertionOptions.cs:line 175
   at FluentAssertions.Equivalency.ValueTypeEquivalencyStep.CanHandle(IEquivalencyValidationContext context, IEquivalencyAssertionOptions config) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\ValueTypeEquivalencyStep.cs:line 17
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 83
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 38
   at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\ObjectAssertions.cs:line 86
   at 
```

### Versions

* Fluent Assertions 5.3.2
* dotnetcore 2.0
* xunit 2.3.1, xunit.runner.visualstudio 2.3.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by benaadams** [comment]
Added an issue to corefx so its easier to find information about this exception in search https://github.com/dotnet/corefx/issues/31186
