### ISSUE TITLE
The non generic BeEquivalentTo throws a NullReferenceException

### ISSUE THREAD

**Issue by Toudahl** [fluentassertions/fluentassertions#877]
### Description

When using BeEquivalentTo on an implementation of System.Data.IDataParameterCollection (a non generic collection) containing a list of System.Data.SqlClient.SqlParameter a null reference exception is thrown

### Complete minimal example reproducing the issue
```csharp
//ARRANGE
var expected = new DataParameterCollection
{
	new SqlParameter{ParameterName = "Id", DbType = DbType.Int32, Value = 1},
};


//ACT
var subjectUnderTest = new DataParameterCollection
{
	new SqlParameter{ParameterName = "Id", DbType = DbType.Int32, Value = 1},
};

//ASSERT
subjectUnderTest.Should().BeEquivalentTo(expected);

```

### Expected behavior:

The assertion should be true.

### Actual behavior:

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.SqlClient.SqlParameter.get_IsNull()

### Versions
.NET Core 2.1

### Additional Information
```csharp
class DataParameterCollection : IDataParameterCollection
{
	private readonly IList _list;

	public DataParameterCollection()
	{
		_list = new List<IDbDataParameter>(); // ArrayList or List<object> gives the same exception
	}
        // Adding this property and using it for the assertion instead solves the issue
	public IList<IDbDataParameter> InternalList => _list as IList<IDbDataParameter>;

	/// <inheritdoc />
	public IEnumerator GetEnumerator() => _list.GetEnumerator();

	/// <inheritdoc />
	public void CopyTo(Array array, int index) => _list.CopyTo(array, index);

	/// <inheritdoc />
	public int Count => _list.Count;

	/// <inheritdoc />
	public bool IsSynchronized => _list.IsSynchronized;

	public object SyncRoot => _list.SyncRoot;

	/// <inheritdoc />
	public int Add(object value) => _list.Add(value);

	/// <inheritdoc />
	public void Clear() => _list.Clear();


	/// <inheritdoc />
	public bool Contains(object value) => _list.Contains(value);

	/// <inheritdoc />
	public int IndexOf(object value) => _list.IndexOf(value);

	/// <inheritdoc />
	public void Insert(int index, object value) => _list.Insert(index, value);

	/// <inheritdoc />
	public void Remove(object value) => _list.Remove(value);

	/// <inheritdoc />
	public void RemoveAt(int index) => _list.RemoveAt(index);

	/// <inheritdoc />
	public bool IsFixedSize => _list.IsFixedSize;

	/// <inheritdoc />
	public bool IsReadOnly => _list.IsReadOnly;

	/// <inheritdoc />
	public object this[int index]
	{
		get => _list[index];
		set => _list[index] = value;
	}

	/// <inheritdoc />
	public bool Contains(string parameterName) => _list.Cast<IDbDataParameter>().SingleOrDefault(p => p.ParameterName.Equals(parameterName)) != null;

	/// <inheritdoc />
	public int IndexOf(string parameterName) =>
		_list.IndexOf(_list.Cast<IDbDataParameter>().SingleOrDefault(p => p.ParameterName.Equals(parameterName)));

	/// <inheritdoc />
	public void RemoveAt(string parameterName) => _list.RemoveAt(IndexOf(parameterName));

	/// <inheritdoc />
	public object this[string parameterName]
	{
		get => _list.Cast<IDbDataParameter>().SingleOrDefault(p => p.ParameterName.Equals(parameterName));
		set => throw new NotImplementedException();
	}
}
```
#### Exception message
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at FluentAssertions.Equivalency.EquivalencyValidationContextExtentions.CreateForNestedMember(IEquivalencyValidationContext context, SelectedMemberInfo nestedMember, SelectedMemberInfo matchingProperty) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidationContextExtentions.cs:line 14
   at FluentAssertions.Equivalency.StructuralEqualityEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\StructuralEqualityEquivalencyStep.cs:line 46
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 85
   at FluentAssertions.Equivalency.EnumerableEquivalencyValidator.TryToMatch[T](Object subject, T expectation, Int32 expectationIndex) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EnumerableEquivalencyValidator.cs:line 132
   at FluentAssertions.Equivalency.EnumerableEquivalencyValidator.LooselyMatchAgainst[T](IList`1 subjects, T expectation, Int32 expectationIndex) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EnumerableEquivalencyValidator.cs:line 103
   at FluentAssertions.Equivalency.EnumerableEquivalencyValidator.AssertElementGraphEquivalency[T](Object[] subjects, T[] expectations) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EnumerableEquivalencyValidator.cs:line 73
   at FluentAssertions.Equivalency.EnumerableEquivalencyValidator.Execute[T](Object[] subject, T[] expectation) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EnumerableEquivalencyValidator.cs:line 40
   at FluentAssertions.Equivalency.EnumerableEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EnumerableEquivalencyStep.cs:line 45
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 85
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Equivalency\EquivalencyValidator.cs:line 38
   at FluentAssertions.Collections.NonGenericCollectionAssertions.BeEquivalentTo(IEnumerable expectation, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\NonGenericCollectionAssertions.cs:line 326
   at Anon.ClassName.BeEquivalantTo_NonGenericList_ShouldNotThrow() in C:\Code\Fluent\src\Project\ClassName.cs:line 10
```

**Comment by dennisdoomen** [comment]
Why does SqlParameter.IsNull throw? Sounds more like a problem with the classes you're comparing than a FA bug.

**Comment by jnyrup** [comment]
From the current .net framework implementation of [SqlParameter](https://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlParameter.cs,70b309b2e92f9495,references)

```csharp
internal bool IsNull {
    get {
        // NOTE: Udts can change their value any time
        if (_internalMetaType.SqlDbType == Data.SqlDbType.Udt) {
            _isNull = ((_value == null) || (_value == DBNull.Value) || ((_isSqlParameterSqlType) && (_valueAsINullable.IsNull)));
        }
        return _isNull;
    }
}
```

Note: We currently do compare internal members, see https://github.com/fluentassertions/fluentassertions/issues/683#issuecomment-338394146

When `IsNull` is invoked `_internalMetaType` is apparently null (I checked it) and hence `IsNull` throws an `NullReferenceException`.
The same problem is the case for the internal properties `CoercedValueIsSqlType` and `CoercedValueIsDataFeed` that also depends on `_internalMetaType` being initialized.

I had a short look at the implementation, but I didn't find a way to initalize `InternalMetaType`.
One possible workaround is to omit comparing the three problematic properties:

```csharp
subjectUnderTest.Should().BeEquivalentTo(expected,
	opt => opt.Excluding(ctx => ctx.SelectedMemberPath.EndsWith("IsNull"))
		.Excluding(ctx => ctx.SelectedMemberPath.EndsWith("CoercedValueIsSqlType"))
		.Excluding(ctx => ctx.SelectedMemberPath.EndsWith("CoercedValueIsDataFeed"))
);
```

**Comment by jnyrup** [comment]
In fact, you don't even need a non-generic collection to hit the exception.

Take two generic lists of the interface `IDbDataParameter` which `SqlParameter` implements.
```csharp
//ARRANGE
var expected = new List<IDbDataParameter>
{
    new SqlParameter{ParameterName = "Id", DbType = DbType.Int32, Value = 1, },
};

//ACT
var subjectUnderTest = new List<IDbDataParameter>
{
    new SqlParameter{ParameterName = "Id", DbType = DbType.Int32, Value = 1},
};
```

If not changed elsewhere 
```csharp
subjectUnderTest.Should().BeEquivalentTo(expected);
```

is equivalent to using [RespectingDeclaredTypes](https://fluentassertions.com/documentation/#compile-time-types-vs-run-time-types)
```csharp
subjectUnderTest.Should().BeEquivalentTo(expected, opt => opt.RespectingDeclaredTypes());
```

Executing this will pass, as it will compare the properties declared on `IDbDataParameter`.

On the other hand, executing:
```csharp
subjectUnderTest.Should().BeEquivalentTo(expected, opt => opt.RespectingRuntimeTypes());
```
will fail, as `BeEquivalentTo` will dig into the runtime type, `SqlParameter` and find `IsNull` and the other internal properties.

The non-generic collections don't have the type information available and hence cannot distinguish between compile-time and and runtime members.

**Comment by dennisdoomen** [comment]
Hmm, should it look at `internal` properties in the first place?

**Comment by jnyrup** [comment]
@dennisdoomen That depends.

For most cases I guess that internal members should not be compared.
I have a library project where I've exposed the internals to a unit test project.
Maybe someone would even like to compare private members?

I can't find anywhere we document that we compare `internal` members.
On the other hand:
https://fluentassertions.com/documentation/#including-properties-andor-fields states:
> Barring other configuration, Fluent Assertions will include all public properties and fields.

and the summaries of `IncludingAllDeclaredProperties()` and `IncludingAllRuntimeProperties()` states:
> Causes inclusion of only public properties [...]

Currently we include: `public`, `internal`, `internal protected` and `private protected` (C# 7.2+)
and exclude `protected` and `private`.

**Comment by jnyrup** [comment]
@Toudahl A much prettier approach for you:
```csharp
subjectUnderTest.Should().BeEquivalentTo(expected,
    opt => opt.Excluding(ctx => ctx.WhichGetterHas(CSharpAccessModifier.Internal)));
```
or

```csharp
subjectUnderTest.Should().BeEquivalentTo(expected,
    opt => opt.Excluding(ctx => ctx.WhichGetterDoesNotHave(CSharpAccessModifier.Public)));
```

**Comment by Toudahl** [comment]
Thank you for the quick responses.

@jnyrup 
Your suggestion gives the same outcome for me.

I will stick to my current workaround, where i expose the internal list of the IDataParameterCollection implementation.

**Comment by jnyrup** [comment]
@Toudahl I hope "same outcome for me" should be interpreted as "it also works around the problem for me".

Otherwise, here's a complete solution with my suggested workarounds
[ConsoleApp35.zip](https://github.com/fluentassertions/fluentassertions/files/2227159/ConsoleApp35.zip)

**Comment by Toudahl** [comment]
I must have made a mistake when i tried it earlier today. It does indeed work as you say.
